const data = [
    {id: "0", departamento: "Huila y Cauca", municipio: "San Agustín y San Sebastián", lugar: "Páramo de las papas / La laguna de la Magdalena", ubicación: "Nacimiento del Rió Magdalena.", n_cientifico: "Leptosittaca branickii", n_comun: "Perico Paramuno", dato: "Es un Psittacido con una coloración principalmente verde y  posee una banda estrecha de color naranja en la frente, la cual se torna un poco más amarilla detrás de los ojos. El periquito paramuno se encuentra en bosques en regeneración o maduros en zonas andinas, alto-andinas o páramos. Tiene un comportamiento gregaria conformando bandadas de diferentes tamaños y es un migratorio estacional con movimiento altitudinales amplios.", fuente: "Palacio, Rubén. 2012.  Perico Paramuno (Lepttositaca branickii). Wiki Aves Colombia. (R. Johnston, Editor). Universidad ICESI. Cali. Colombia.http://www.icesi.edu.co/wiki_aves_colombia/tiki-index.php?page_ref_id=1460 PLAN DE MONITOREO LEPTOSITTACA BRANICKII EN EL ÁREA CLAVE DE LA BIODIVERSIDAD Y CONSERVACIÓN ACB-PÁRAMO DEL DUENDE. ANDRÉS GÓMEZ FIGUEROA"},
    {id: "1", departamento: "Huila", municipio: "San Agustín", lugar: "", ubicación: "Ubicado en el alto valle del Río Magdalena.", n_cientifico: "Rhetus arcius", n_comun: "Mariposa Azul de Cola Larga", dato: "Esta especie se encuentra distribuida en México, Colombia, Costa Rica, Ecuador, Panamá, Venezuela y Perú. Sus larvas y  adultos se caracterizan por su alta diversidad morfologica. Se puede encontrar comunmente cerca a cuerpos de agua, en las arenas húmedas.", fuente: "Hall, Jason P. W.; Harvey, Donald J. (2002). «A survey of androconial organs in the Riodinidae (Lepidoptera)». Zoological Journal of the Linnean Society 136: 171-197. doi:10.1046/j.1096-3642.2002.00003.x. Consultado el 30 de agosto de 2014."},
    {id: "2", departamento: "Huila", municipio: "Neiva", lugar: "", ubicación: "Ubicado en el alto valle del Río Magdalena", n_cientifico: "Pyrocephalus rubinus", n_comun: "Atrapamoscas pechirojo", dato: "Tambien es conocido como Titiribí.Es una especie que presenta dimorfismo sexual, los machos presentan en la coronilla y partes inferiores un color rojo escarlata brillante; mientras que las hembras tienen coloraciones cafes, y blancas grisaceas y en las partes inferiores un color salmon rosáceo. Se encuentran en terrenos secos y abiertos con árboles y rastrojo, tambien en parques y jardines.", fuente: "\n > Universidad ICESI. Pyrocephalus rubinus. https://www.icesi.edu.co/wiki_aves_colombia/tiki-index.php?page=Atrapamoscas+PechirrojoHilty \n > S. L. y W. L. Brown. 2001. Guía de las Aves de Colombia. Cali. American Bird Conservancy, Sociedad Antioqueña de Ornitologia, Universidad del Valle."},
    {id: "3", departamento: "Cundinamarca", municipio: "Girardot", lugar: "", ubicación: "Ubicado en la provincia del alto Magdalena.", n_cientifico: "Brownea ariza", n_comun: "Arbol de la Cruz", dato: "Se llama popularmente árbol de cruz o palo de cruz, es un árbol nativo de Colombia, Ecuador y Venezuela. Es una especie maderable, ornamental y eficaz en la protección de las fuentes hidricas. Posee una madera dura y resistente al ataque de termitas y algunas de las partes del árbol son usadas en la medicina tradicional.", fuente: "https://www.monaconatureencyclopedia.com/brownea-ariza/?lang=es"},
    {id: "4", departamento: "Tolima", municipio: "Honda", lugar: "", ubicación: "Ubicado en el valle del Magdalena Medio, sin embargo tiene caracteristicas de un valle interandino estrecho.", n_cientifico: "Ortalis columbiana", n_comun: "Guacharaca colombiana", dato: "Es una especie de ave endémica de Colombia. Se alimenta principalmente de frutos, siendo un dispersor importante de semillas. Se puede observar en bosques húmedos, premontanos, bordes de bosques y zonas arboladas. A menudo se les ve tambien en áreas urbanas y periurbanas.", fuente: "Delgado, M. E. 2010. Guacharaca Colombiana (Ortalis columbiana). Wiki Aves Colombia. (R. Johnston, Editor). Universidad ICESI.  Cali. Colombia. https://www.icesi.edu.co/wiki_aves_colombia/tiki-index.php?page=Guacharaca+Colombiana"},
    {id: "5", departamento: "Caldas", municipio: "La Dorada", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio.", n_cientifico: "Anolis gaigei", n_comun: "Anolis de Gaigei", dato: "Se le conoce comunmente como lagartija, y se encuentra en la vegetación razante y  arbustiva de diferentes coberturas. La especie se encuentra en Colombia y Panamá. Los machos igual que en muchas otras especies de anolis, poseen gulas que son abanicos que se extienden desde su garganta, en el caso de esta especie su gula es de color amarillo-naranja y sirve particularmente para la comunicación entre los individuos.", fuente: "https://www.researchgate.net/profile/Juan-Costa-4/publication/343112480_LA_GULA_COMO_INDICADOR_DE_VIGOROSIDAD_EN_LA_LAGARTIJA_Norops_cupreus/links/5f1780d592851cd5fa3be3e6/LA-GULA-COMO-INDICADOR-DE-VIGOROSIDAD-EN-LA-LAGARTIJA-Norops-cupreus.pdf"},
    {id: "6", departamento: "Boyacá", municipio: "Puerto Boyacá", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio.", n_cientifico: "Ateles hybridus", n_comun: "Mono araña del Magdalena", dato: "Son primates que habitan principalmente en el dosel, en donde consiguen frutos maduros, hojas y pequeños artrópodos de los que se alimentan. Su principal movimiento en el dosel lo hacen balanceandose con sus brazos para poder desplazarse. La cola que poseen es prensil muy larga que funciona como una quinta extremidad.", fuente: "http://historianatural.unal.edu.co/expo1/mono.html"},
    {id: "7", departamento: "Antioquia", municipio: "Puerto Nare", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio.", n_cientifico: "Dendropsophus ebraccatus", n_comun: "Rana arborea amarillenta", dato: "Esta rana tiene habitos nocturnos y arboricolas. Suele habitar bosque humedos primarios y secundarios. Tiene una gran variedad en sus patrones en su coloración dorsal. Esta especie presenta plasticidad en su modo reproductivo, es decir, que lo modifica con relación a las condiciones del medio. Cuando hay una fuerte radiación solar en la zona las hembras depositaran sus huevos en el agua evitando la desecación, mientras que cuando el area tiene mayor cobertura y menos radiación solar podran depositar por huevos fuera del agua sobre las hojas.", fuente: "\n > Read, M., Ron, S. R. y Pazmiño-Armijos, G. 2022. Dendropsophus ebraccatus En: Ron, S. R., Merino-Viteri, A. Ortiz, D. A. (Eds). Anfibios del Ecuador. Version 2021.0. Museo de Zoología, Pontificia Universidad Católica del Ecuador. https://bioweb.bio/faunaweb/amphibiaweb/FichaEspecie/Dendropsophus%20ebraccatus, acceso miércoles, 21 de Septiembre de 2022 \n > Ospina-L, Ana María & Touchon, Justin. (2018). Dendropsophus ebraccatus. 4. 37-47."},
    {id: "8", departamento: "Antioquia", municipio: "Puerto Berrío", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio.", n_cientifico: "Micrurus dumerilii", n_comun: "Coral", dato: "Es una serpiente venenosa de la familia Elapidae. Sus patrones de actividad se han identificado en las primeras horas de la mañana, al atardecer o en las primeras horas de la noche. Su mordedura es de importanica medica en humanos ya que su veneno es neurotóxico y genera parálisis de los músculos; posee un par de colmillos muy cortos ubicados en la parte anterior de la boca, es decir su dentición es proteroglifa.", fuente: "\n > Rodríguez-Guerra, A. 2020. Micrurus dumerilii En: Torres-Carvajal, O., Pazmiño-Otamendi, G., Ayala-Varela, F. y Salazar-Valenzuela, D. 2021. Reptiles del Ecuador. Version 2021.0. Museo de Zoología, Pontificia Universidad Católica del Ecuador. https://bioweb.bio/faunaweb/reptiliaweb/FichaEspecie/Micrurus%20dumerilii, acceso Miércoles, 21 de Septiembre de 2022. \n > Suárez, Ana María y Esteban Alzate Basto. 2014. Guía Ilustrada Anfibios y reptiles Cañón del río Porce, Antioquia. EPM E.S.P. Universidad de Antioquia, Herbario Universidad de Antioquia - Medellín, Colombia. 138 pp."},
    {id: "9", departamento: "Santander", municipio: "Barrancabermeja", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio.", n_cientifico: "Cecropia peltata", n_comun: "Yarumo", dato: "El Yarumo es un arbol hasta de 20 metros de altura, sus tallos pueden ser utilizados en la fabricación de instrumentos musicales y otras artesanias. Posee  frutos que son consumidos por aves y murciélagos.", fuente: "David H., H., O. Díaz V., L.M. Urrea & F. Cardona N. 2014. Guía Ilustrada Flora Cañón del río Porce, Antioquia. EPM E.S.P. Universidad de Antioquia, Herbario Universidad de Antioquia - Medellín, Colombia. 264 pp."},
    {id: "10", departamento: "Santander", municipio: "Puerto Wilches", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio.", n_cientifico: "Xenesthis immanis", n_comun: "Tarantula Purpura", dato: "Es una araña relativamente grande. Presenta coloraciones purpuras en su dorso. Los machos son más activos que las hembras quienes suelen permanecer la mayor parte del tiempo dentro de su madriguera. Se alimenta de insectos y pequeños roedores. Se ha visto que esta tarantula tiene una relación mutualista con una rana de la familia Microhylidae, en la que la araña protege a la rana y sus huevos de los depredadores, mientras que la rana protege los huevos de la araña de las hormigas.", fuente: "http://historianatural.unal.edu.co/expo1/tarantula.html"},
    {id: "11", departamento: "Bolívar", municipio: "San Pablo", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio.", n_cientifico: "Potamotrygon magdalenae", n_comun: "Raya del Magdalena", dato: "Es una raya dulceacuicola, de hábitos bentónicos y se alimenta de moluscos, renacuajos, peces, insectos, otros artrópodos y detritos, tiene preferencia sobre aguas turbias, fondos de arena y fango.  Es frecuente encontrarla en el cauce principal de los ríos Magdalena y Atrato.", fuente: "http://historianatural.unal.edu.co/expo1/raya.html"},
    {id: "12", departamento: "Cesar", municipio: "Gamarra", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio.", n_cientifico: "Cedrela odorata", n_comun: "Cedro", dato: "Es una especie con un importante potencial para procesos de restauración de zonas degradadas. Cedrela: de Cedrus, por su similaridad con la madera de este género. Odorata, significa perfumado, oloroso, por su madera. Se encuentro en amenza y su estado de conservación es: En Peligro.", fuente: "http://www.conabio.gob.mx/conocimiento/info_especies/arboles/doctos/36-melia2m.pdf"},
    {id: "13", departamento: "Cesar", municipio: "Tamalameque", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio.", n_cientifico: "Epicrates maurus", n_comun: "Boa chocolate/Boa arcoiris café", dato: "Es una serpiente NO venenosa y constrictora. Su coloración puede ser homogenea y marron o presentar algunos anillos un poco más oscuros. Epicrates viene de la palabra griega kratos que significa poder y maurus piel oscura. Se alimentan principalmente de lagartijas, aves y pequeños mamíferos.", fuente: "Serpentario Nacional de Colombia"},
    {id: "14", departamento: "Magdalena", municipio: "El banco", lugar: "", ubicación: "Ubicado en la región del Magdalena Medio y Forma parte de la Depresión momposina.", n_cientifico: "Eira barbara", n_comun: "Tayra/Viejo de Monte", dato: "Es una especie de mamifero diurno-crepuescular. Suele ser solitaria y presenta desplazamientos amplios dentro de los territorios. Se alimenta de frutas y pequeños vertebrados, principalmente de los arbóreos. Son muy ágiles para desplazarse, tanto en el suelo como en lo alto de los árboles.", fuente: "Vallejo, A. F 2022. Eira barbara En: Brito, J., Camacho, M. A., Romero, V. Vallejo, A. F. (eds). Mamíferos del Ecuador. Version 2018.0. Museo de Zoología, Pontificia Universidad Católica del Ecuador. https://bioweb.bio/faunaweb/mammaliaweb/FichaEspecie/Eira%20barbara, acceso Jueves, 22 de Septiembre de 2022."},
    {id: "15", departamento: "Bolívar", municipio: "Santa Cruz de Mompox", lugar: "", ubicación: "Ubicado en la región del bajo Magdalena y Forma parte de la Depresión momposina.", n_cientifico: "Megaceryle torquata", n_comun: "Matin pescador mayor", dato: "Esta ave se observa generalmente perchado pacientemente en ramas que sobresalen por encima de cuerpos de agua loticos y lenticos. Se lanza al agua en donde captura sus presas las cuales lleva a la percha para golpearlas y engullirlas. Ademas de los peces consume  ranas, salamandras, reptiles, cangrejos e insectos.", fuente: "Arango, C. A. 2012. Martín-Pescador Mayor(Megaceryle torquata). Wiki Aves Colombia. (R. Johnston, Editor). Universidad ICESI.  Cali. Colombia. http://www.icesi.edu.co/wiki_aves_colombia/tiki-index.php?page_ref_id=1659"},
    {id: "16", departamento: "Bolívar", municipio: "Magangué", lugar: "", ubicación: "Ubicado en la región del bajo Magdalena y Forma parte de la Depresión momposina.", n_cientifico: "Podocnemis lewyana", n_comun: "Tortuga del Río Magdalena", dato: " Es una especie categorizada como: En Peligro. Es una tortuga dulceacuicola y se encuentra en ríos, caños, ciénagas y áreas inundadas. Principalmente  presenta una dieta herbívora y frugívora, muy ocasionalmente carnívora. Las  hembras son más grandes que los machos. Pueden observarse tomando el sol a lo largo de las orillas o sobre árboles caídos.", fuente: "\n > http://reporte.humboldt.org.co/assets/docs/2016/2/201/libro-rojo-de-reptiles/31-podocnemis-lewyana.pdf \n > Páez, Vivian & Restrepo, Adriana & Vargas-Ramírez, Mario & Bock, Brian & García, Natalia. (2013). Podocnemis lewyana (Dumeril 1852). Catálogo de anfibios y reptiles de Colombia. 1. 1-5."},
    {id: "17", departamento: "Magdalena", municipio: "Plato", lugar: "", ubicación: "Ubicado en la región del bajo Magdalena.", n_cientifico: "Caiman crocodilus", n_comun: "Babilla", dato: "Es una especie de habitos principalemente nocturnos. En el dia se observan tomando el sol sobre la rivera de los cuerpos de agua lenticos y loticos.  Presenta un comportamiento más gregario a diferencia de otras especies. Son animales carnívoros, generalistas. Su dieta varía según su etapa de desarollo, teniendo relación con el tamaño de los individuos.", fuente: "Ortiz, D. A., Carvajal-Campos, A. y Rodríguez-Guerra, A. 2019. Caiman crocodilus En: Torres-Carvajal, O., Pazmiño-Otamendi, G., Ayala-Varela, F. y Salazar-Valenzuela, D. 2021. Reptiles del Ecuador. Version 2021.0. Museo de Zoología, Pontificia Universidad Católica del Ecuador. https://bioweb.bio/faunaweb/reptiliaweb/FichaEspecie/Caiman%20crocodilus, acceso Jueves, 22 de Septiembre de 2022."},
    {id: "18", departamento: "Bolívar", municipio: "Calamar", lugar: "", ubicación: "Ubicado en la región del bajo Magdalena y hace parte del canal del Dique.", n_cientifico: "Artibeus lituratus", n_comun: "Murciélago frutero grande", dato: "Es un murcielago de gran tamaño. Su dieta esta compuesta principalmente por frutos y bayas, ocasionalmente puede consumir insectos y nectar de las flores. Suelen buscar refugio durante el dia en árboles huecos, entre las hojas de las palmas, en cuevas o debajo de puentes.", fuente: "Romero, V. 2022. Artibeus lituratus En: Brito, J., Camacho, M. A., Romero, V. Vallejo, A. F. (eds). Mamíferos del Ecuador. Version 2018.0. Museo de Zoología, Pontificia Universidad Católica del Ecuador. https://bioweb.bio/faunaweb/mammaliaweb/FichaEspecie/Artibeus%20lituratus, acceso Jueves, 22 de Septiembre de 2022."},
    {id: "19", departamento: "Magdalena", municipio: "Remolino", lugar: "", ubicación: "Ubicado en la región del bajo Magdalena.", n_cientifico: "Chauna chavaria", n_comun: "Chavarri", dato: "Se encuentra en tierras bajas en pantanos, lagunas con gran vegetación en sus alrededores, madreviejas y áreas abiertas o boscosas. Se considera un ave especialista y se alimenta principalmente de la vegetación semi acuática. Se encuentran solitarios, en parejas o grupos pequeños. Son de carácter tranquilo, pero cuando se encuentran en celo pueden tornarse agresivos. Su canto es muy sonoro parecido al sonido de una trompeta, lo que permite su fácil ubicación.", fuente: "Delgado, M. E. 2010. Chavarría (Chauna chavaria). Wiki Aves Colombia. (R. Johnston, Editor). Universidad ICESI.  Cali. Colombia. http://www.icesi.edu.co/wiki_aves_colombia/tiki-index.php?page=Chavarria&page_ref_id=433"},
    {id: "20", departamento: "Atlántico", municipio: "Sabanagrande", lugar: "", ubicación: "Ubicado en la región del bajo Magdalena.", n_cientifico: "Ceratophrys calcarata", n_comun: "Sapo cornudo", dato: "Este sapo se caracterisa por presentar una cabeza grande con unas poryecciones dermicas en forma de cuernos sobre sus ojos. Se encuentra en tierras bajas de la región caribe. La dieta de este sapo esta compuesta en su mayoria por ranas de menor tamaño y por artropodos.", fuente: "Pérez, Oskarly & Cervantes, Germán. (2016). Ecología trófica del “sapo cuerno” (Ceratophrys calcarata, Boulenger 1890) (Anura: Ceratophryidae), en La Avianca, Magdalena, Colombia. Revista Biodiversidad Neotropical. 6. 27. 10.18636/bioneotropical.v6i1.226."},
    {id: "21", departamento: "Atlántico", municipio: "Barranquilla", lugar: "", ubicación: "Desembocadura del río Magdalena.", n_cientifico: "Anhinga anhinga", n_comun: "Pato aguja", dato: "Suele verse en cuerpos de agua continentales poco profundos, especialmente lagos, rios de flujo lento y pantanos. Sin embargo, tambien se encuentra en areas salobres como estuarios y manglares.  Dentro de sus habitos dietarios se encuentra la preserencia por peces, crustáceos, ranas, salamandras, renacuajos, serpientes, crías de cocodrilo, insectos acuáticos y sus larvas.  Este pago es buen nadador y suele capturar sus presas bajo el agua. Se les observa sobre rocas con sus alas extendidas o solo con su cuello y cabeza por fuera del agua.", fuente: "Arango, C. 2014. Pato Aliverde (Anas crecca). Wiki Aves Colombia. (C. Arango, Editor) . Universidad ICESI. Cali. Colombia. http://www.icesi.edu.co/wiki_aves_colombia/tiki-index.php?page_ref_id=1233"},
    {id: "22", departamento: "Atlántico", municipio: "Barranquilla", lugar: "Bocas de Ceniza ", ubicación: "Desembocadura del río Magdalena.", n_cientifico: "Trichechus manatus", n_comun: "Manatí­ del Caribe", dato: "Se encuentra en aguas costeras, en estuarios, en la desembocadura de los ríos en el mar. Toleran grandes cambios en la salinidad del agua. Se consideran oportunitas segun la disponibilidad de alimento. Poseen pelos gruesos y sensoriales en su hocico.", fuente: "https://omacha.org/manaties/"}
]


var rio_mag = document.querySelectorAll(".group-rio"); 
var div = document.createElement("DIV")

function showInfo(data) {
    let lugarEsp = "";

    if (data.lugar !== "") {
        lugarEsp = "<b> Lugar Específico: </b> " + data.lugar;
    } 

    div.innerHTML = `
        <b> Departamento: </b> ${data.departamento} <br>
        <b> Municipio: </b> ${data.municipio} <br>
        <b> Ubicación: </b> ${data.ubicación} <br>
        ${lugarEsp} <br><br>
        <b> * Especie que puedes encontrar en la Zona: </b> <br>
        <b> Nombre científico: </b> <i> ${data.n_cientifico} </i> <br>
        <b> Nombre Común: </b> ${data.n_comun} <br>
        <b> Dato de la especie: </b> ${data.dato} <br><br>
        <b> Fuente: </b> ${data.fuente.replace(/\n/g, "<br />")} 
    `
}

rio_mag.forEach(el => {
    el.addEventListener("mouseover", (event) => {
        console.log(event)
        for (var i=0; i<data.length; i++) {
            if (data[i].id === event.target.id) {
                showInfo(data[i])
            }   
                           
        }   
    })
})

$(function () {
    $('[data-toggle="tooltip"]').tooltip({
        boundary: "viewport",
        template: `
            <div class="tooltip" role="tooltip" style="width: 35%">
                <div class="arrow"></div>
                <div class="tooltip-inner" 
                    style="
                        max-width: none;
                        background:rgb(235, 235, 235); 
                        color:black; 
                        box-shadow: rgb(207, 207, 207) .5px .5px 4px;
                        text-align: left;
                        font-family: verdana;
                        font-size: 12px;                         
                    ">
                </div>
            </div>`,
        title: div,
    })
})
