const data = [
    {id: "0", cordillera: "Oriental", distrito: "Páramos Perijá (4.562 ha)", complejo: "Perijá", generalidades: "Se ubica en la Serranía de Perijá entre el límite de norte de Colombia y Venezuela, cuenta con 28.984 ha, tiene un rango latitudinal 3.100-3.600 msnm.", fauna_flora: "Se ha registrado difrentes especies como lo son el Jaguar, Oso andino, El Cóndor de los Andes,La Perdiz carinegra, el Toro de Monte, Frailejón de Perijá, Salvia de Cerro Pintado, Alhucema del Cerro Pintado y Salvia de Manaure.", datos: "Dentro de este complejo se encuentra el resguardo Iroka en 1.245 ha"},
    {id: "1", cordillera: "Oriental", distrito: "Páramos de los santanderes (215.716 ha)", complejo: "Santúrban", generalidades: "Se localiza entre Norte de Santander y Santander, cuenta con 82.664 ha, entre los 3.000 y 4.290 msnm.", fauna_flora: "Algunas especies se encuentran en peligro de extinción como el Venado de páramo, el cóndor, pato de páramo.", datos: ""},
    {id: "2", cordillera: "Oriental", distrito: "Páramos de los santanderes (215.716 ha)", complejo: "Tamá", generalidades: "Se encuentra en el departamento de Norte de Santander y ocupa cerca de 7.110 ha, entre los 3.000 y 3.640 msnm", fauna_flora: "De las especies mas representativas son el oso andino, venados, lapas o guartinajas, puma, rana marsupial de color amarillo, guacharos y colibrí de páramo. Especies de flora se encuentra el frailejón arboleo y la Tamania chardonii", datos: ""},
    {id: "3", cordillera: "Oriental", distrito: "Páramos de los santanderes (215.716 ha)", complejo: "Almorzadero", generalidades: "Se ubica entre los departamentos de Santander y Norte de Santander, comprende 125.120 ha y un rango latitudinal entre 3100 y 4.530 msnm", fauna_flora: "Se ha registrado difrentes especies como lo son el Jaguar, Oso andino, Espeletia dugandii y Puya garganta, El Cóndor de los Andes , El chango de montaña, El periquito aliamarillo ,  El águila crestada, ranas arlequí. ", datos: "Resguardo indígena Unido U´wa con 6.242 ha"},
    {id: "4", cordillera: "Oriental", distrito: "Páramos de los santanderes (215.716 ha)", complejo: "Yariguíes", generalidades: "Se ubica en el departamento de Santander, entre los 3.050 y 3.410 msnm con 812 ha.", fauna_flora: "La vegetación se encuentra caracterizada por una vegetaciín de chusques y gramíneas. Algunas especies de aves criticamente amenazadas están la perdiz santandereana, cucarachero pechirrufo y el torito capiblanco.", datos: "No se encuentran asentamientos humanos"},
    {id: "5", cordillera: "Oriental", distrito: "Páramos de Boyacá (594.048 ha)", complejo: "Cocuy", generalidades: "Se encuentra conformado por el sistema de alta montaña entre el norte de Boyacá, el oriente de Santander, occidente de Arauca , noroccidente de Casanare y el sur de Norte de Santander , con 268.783 ha", fauna_flora: "Constituye una gran variedad de frailejones, se presencia mamíferos como el oso de anteojos, el zorro, venado de cola blanca, la comadreja y la musaraña.Aves como el colibrí paramuno, cometa colinegro, metalura colirrojo, coludito frailejonero, chirlobiro, cucarachero de Apolinar y mirla.", datos: "Se encuentra cinco grupos indígenas de las etnias u´wa y tunebo, los cuales ocupan casi 80.000 ha."},
    {id: "6", cordillera: "Oriental", distrito: "Páramos de Boyacá (594.048 ha)", complejo: "Pisba", generalidades: "Se ubica entre los departamentos de Boyacá y Casanare, sobre los 3.100 - 4.100 msnm con una extensión de 81.481 ha.", fauna_flora: "En fauna se ha identificado frailejones, pajonales-churruscales, frailejones-romerales, arnica y musgos. En flora se ha identificado mamíferos como el cusumbo, venado de cola blanca, conejo, venado locho y oso andino.", datos: ""},
    {id: "7", cordillera: "Oriental", distrito: "Páramos de Boyacá (594.048 ha)", complejo: "Tota-Bijagual-Mamapacha", generalidades: "Se encuentra ubicado en el departamento de Boyacá, entre los 3.100-3.970 msnm con 127.310 ha", fauna_flora: "Se han registrado una gran cantidad de especies de fauna y flora.", datos: ""},
    {id: "8", cordillera: "Oriental", distrito: "Páramos de Boyacá (594.048 ha)", complejo: "Guantiva-Rusia", generalidades: "Se encuentra ubicado entre los departamentos de Boyacá y Santander, a 3.100-4.280 msmm y ocupa un área de 100.262 ha.", fauna_flora: "Flora: predomina los chuscales y diferentes tipos de Espeletia. Fauna: se ha registrado especies en estado de categoría de amenaza como lo es el oso de anteojos, la cotorra montañera, gallito de roca, pavas de monte, y algunos venados.", datos: ""},
    {id: "9", cordillera: "Oriental", distrito: "Páramos de Boyacá (594.048 ha)", complejo: "Iguaque-Merchán", generalidades: "Se ubica en los departamentos de Boyacá y Santander ,entre los 3.150 y 3.820 msnm en 16.212 ha.", fauna_flora: "La fauna y flora se ubica dentro de la zona geográfica de andina y de páramo. Según el plan de manejo de la zona reporta algunos mamíferos como las faras, murciélagos, ardillas, curies silvestres, zorros, comadrejas, ulama o umba, guaches o carijingos, venados soche y blancos, tigrillos y armadillos.", datos: "La población en su gran mayoria es campesina. Desde la perspectiva cultural el santurario es considerado por los muiscas como la cuna de la humanidad, ya que de esa laguna salio Bachué y Labaque."},
    {id: "10", cordillera: "Oriental", distrito: "Páramos de Cundinamarca (386.869 ha)", complejo: "Guerrero", generalidades: "Se ubica en el norete de Cundinamarca, entre los 3.200 -3.700 msn y ocupa alrededor de 39.240 ha", fauna_flora: "Se identificaron tres unidades de vegetación: páramo, bosques altoandinos y vegetación de subpáramo.Por otra parte, el complejo guerrero ha perdido una gran cantidad de fauna original, como el puma, oso de anteojos, danta de páramo, venado matacán andino, venado de cola blanca y el gato de monte.", datos: "Las principales actividades que se realizan en este páramo se encuentran relacionadas con los sitemas agropecuarios. "},
    {id: "11", cordillera: "Oriental", distrito: "Páramos de Cundinamarca (386.869 ha)", complejo: "Rabanal", generalidades: "Se ubica en el altiplano cundiboyacense, sobre los 3.200-3585 msnm t con 16.356 ha", fauna_flora: "Los principales tipos de vegetación registrados en la zona son rosetales, prados de páramo y pajonales, además es común tener al frailejón. Se ha registrado la presencia de curíes, armadillos, guaches, faras, conejos ardillas, ya se dice que se encuentran extintas por esta zona algunos animales como los pumas, el oso frontino y la danta de páramo", datos: "Actualmente la población se dedica a las labores agropecuarias"},
    {id: "12", cordillera: "Oriental", distrito: "Páramos de Cundinamarca (386.869 ha)", complejo: "Chingaza", generalidades: "Se ubica entre los departamentos de Cundinamarca y el Meta, sobre los 3.150-3.980 msnm y ocupa alrededor de 64.500 ha. ", fauna_flora: "Se destacan especies endémcas como los frailejones, las árnicas y el tuno. Resaltan especies de fauna como el chivito de páramo, colibrí gigante, la ardilla, el cóndor de los andes, oso andino, venado cola blanca y el colorado, el borugo de páramo, gallito de roca y el puma.", datos: "Chingaza fue considerado como santuario supremo para la cultura muisca, en el cual, las lagunas, las montañas y en especial el agua presentaba un gran valor."},
    {id: "13", cordillera: "Oriental", distrito: "Páramos de Cundinamarca (386.869 ha)", complejo: "Sumapaz", generalidades: "Se encuentra al suroeste de Cundinamarca , noreste del Meta e incluye una pequeña parte del Huila. Se sitúa entre los 3.250-4.230 msnm y ocupa alrededor de 26.750 ha", fauna_flora: "La vegetación se encuentra conformada por chuscales, matorrales bajos y herbazales, frailejones, entre otros. Se ha registrado mamíferos como el conejo de páramp, curí, venado blanco o de páramo, venado soche, danta de páramo, tigrillo, oso de anteojos,cusumbo y zorro de bosque, ademas se ha reportado la presencia de aves como el águila real, pato turria, pato de páramo, caica y tominejos ", datos: "Las principales actividades que se realizan en este páramo se encuentran relacionadas con los sitemas agropecuarios. Y en algunos casos mineria de recebo para el mantenimiento de carreteras."},
    {id: "14", cordillera: "Oriental", distrito: "Páramos los Picachos (3.819 ha)", complejo: "Los Picachos", generalidades: "Se encuentra ubicado en los departamentos de Caquetá y el Meta, con 3.819 ha sobre 3.250-3.620 msnm", fauna_flora: "La flora de este complejo corresponde a una vegetación herbácea y especies de fauna se ha reportado la presencia del oso de anteojos y el venado enano.", datos: "Para la zona de páramos se ha reportado la presencia de agroecosistemas asociados a páramo."},
    {id: "15", cordillera: "Oriental", distrito: "Páramos Miraflores (2.903 ha)", complejo: "Miraflores", generalidades: "Se ubica en los departamentos de Huila y Caquetá, con una extensión de 2.903 ha sobre los 3.300-3.470 msnm", fauna_flora: "Se presencia diferentes tipos de vegetación como bosque natural, bosque secundario, rastrojo, matorral de páramo, pajonales y bosque achaparrado. En relación a la fauna se ha presenciado el periquito de los Nevados. ", datos: "No se han identificado asentamientos humanos"},
    
    {id: "16", cordillera: "central", distrito: "Páramos Belmira (1.080 ha)", complejo: "Belmira", generalidades: "Se ubica en departamento de Antioquia sobre los 3.100-3.340 msnm con un total de 1.080 ha.", fauna_flora: "La especie de flora mas abundante es el frailejón, y algunas especies en estado vulnerable como el saltacalenon, mote, romero de páramo, helecho, mortiño y marrana.  En cuanto a fauna se destaca la presencia de zorros y pumas,  además se desataca que anteriormente se avistaba el oso andino y venado cola blanca.", datos: "No hay evidencia de presencia de resguardos indígenas"},
    {id: "17", cordillera: "central", distrito: "Páramo Viejo Caldas -Tolima (129.957 ha)", complejo: "Nevados", generalidades: "Se encuentra ubicado entre los departamentos de Caldas, Risaralda, Quindío y Tolima. Sobre los 3.550-5.280 msnm y ocupa alrededor de 102.054 ha.", fauna_flora: "Se distingue vegetación de superpáramo, zona glaciar, prados secos, turberas, matorrales y bosques achaparrados. Se registra diferentes tipos de anfibios, de aves como el pato paramuno, el turpial, el guardacaminos, el guaraguao, la diglosa, la pizarra, la golondrina azul y el tucán andino, por otro lado, la presencia del tapir de montaña, el oso de anteojos, el borugo y el cusumbo.", datos: ""},
    {id: "18", cordillera: "central", distrito: "Páramo Viejo Caldas -Tolima (129.957 ha)", complejo: "Chilí-Barragán", generalidades: "Se ubica en el departamento del Tolima sobre los 3.400-4.040 msnm con una extensión de 27.900 ha", fauna_flora: "Se carateriza la vegetación de bosque bajo denso, pajonal y humedales, de especies de fauna se ha avistado el tororoi medialuna, cotorra, periquito de páramo y el loro cejidorado. Por otra parte, los mamíferos más concocidos son el oso de anteojos, la boruga de páramo, venado enano y el cusumbo", datos: ""},
    {id: "19", cordillera: "central", distrito: "Páramos Valle-Tolima (183.648 ha)", complejo: "Las Hemosas", generalidades: "Se ubica en los departamentos de Tolima, Valle del Cauca y Cauca, sobre los 3.450-4.580 msnm y ocupa un área de 115.682 ha.", fauna_flora: "En flora este páramo se caracteriza por tener una cobertura boscosa con estratos de árboles y arbustos. Se destaca la presencia del oso de anteojos, venado coliblanco y la danta de montaña", datos: "La población indígena en el sector del Valle del Cauca está compuesta por comunidades del resguardo KwetWala, en relación a la zona de Tolima comunidades de pijao y nasa."},
    {id: "28", cordillera: "central", distrito: "Páramos Valle-Tolima (183.648 ha)", complejo: "Nevado de Huila-Moras", generalidades: "Se ubica en los departamentos de Cauca, Huila y Tolima , sobre los 3.500-5.380 msnm y con una extensión de 67.966 ha", fauna_flora: "Se presencia especies como el romero de páramo, gramíneas y pajonales. Especies de fauna se ha identificado aves como el águila real, colibrí, el gavilán, guácharo y el cóndor. Además se identificado algunos mamíferos como el oso de anteojos, danta de páramo y el tigrillo.", datos: "Actualmente el complejo se encuentra el resguardado indígena Jambaló."},
    {id: "21", cordillera: "central", distrito: "Páramos Macizo Colombiano (109.812 ha)", complejo: "Guanacas-Puracé-Coconucos", generalidades: "Se ubica en los departamentos de Cauca y Huila, sobre los 3.350-4.640 msnm con una extensión de 72.350 ha", fauna_flora: "Se caracteriza la vegetación de bosque andino y altoandino. Algunas especies de fauna se encuentran en estado vulnerable como el azulejo de Wetmore, pato andino y pato golondrino. De mamíferos se encuentra la danta de páramo,el tigrillo gallinero, el puma y el oso andino.", datos: "Se encuentra habitado por un espacio de descendientes de comunidades precolombinas como Kookonucos, yanaconas y papallacta."},
    {id: "22", cordillera: "central", distrito: "Páramos Macizo Colombiano (109.812 ha)", complejo: "Sotará", generalidades: "Se ubica en los departamentos de Cauca y Huila, con una extensión de 3.350-4.400 msnm y una ocupación de 37.462 ha", fauna_flora: "Las especies de fauna más representativas son el frailejón, gramineas, helechos y arbustos. Por otra parte se ha presenciado eloso andino, venado conejo, tigrillo, la danta de montaña y el puma.", datos: "La cultura muisca es la base para transmitir a los indigenas y campesinos las tradiciones antiguas."},
    
    {id: "23", cordillera: "Occidental", distrito: "Páramo Paramillo (1.549 ha)", complejo: "Paramillo", generalidades: "Se encuentra ubicado en el departamento de Antioquia, entre los 3.300- 3.720 msnm y con un area de 1.550 ha", fauna_flora: "Vegetación de páramo de sabana, se ha identificado la diglosa el cual se encuentra en estado vulnerable", datos: ""},
    {id: "24", cordillera: "Occidental", distrito: "Páramos Frontino-Tatamá (10.429 ha)", complejo: "Frontino", generalidades: "Se encuentra en el departamento de Antioquia y una parte de Chocó, sobre los 3.400-3.930 msnm con una ocupación de 4.030 ha", fauna_flora: "La vegetación se caracteriza por se abierta no boscosa propia de páramo. Especies de fauna reportada: oso de anteojos, cuzumbo, salamandra no pulmonada, colibríes, y cotorra montañera.", datos: "Antes de la llegada de los españoles la region se encontraba habitada por indígenas de la etnia katía."},
    {id: "25", cordillera: "Occidental", distrito: "Páramos Frontino-Tatamá (10.429 ha)", complejo: "Citará", generalidades: "Se encuentra ubicado en los departamentos de Antioquia, Chocó y Risaralda. Sobre los 3.350-3.970 msnm y ocupa 2.150 ha", fauna_flora: "Se caracteriza por tener bosque achaparrado, con presencia de zarigueyas, guagua, ñeque, ardilla y armadillos", datos: "Las tribus indígenas que se encontraban anteriormente en el complejo de citará pertenecían a las etnias citares y tapartoes."},
    {id: "26", cordillera: "Occidental", distrito: "Páramos Frontino-Tatamá (10.429 ha)", complejo: "Tatamá", generalidades: "Se encuentra ubicado en los departamentos de Chocó y Risaralda, sobre los 3.450-4.070 msnm y una ocupación de 4.200 ha", fauna_flora: "La vegetación se entremezcla entre el bosque andino y páramo arbustivo.", datos: "No se han identificado asentamientos humanos"},
    {id: "27", cordillera: "Occidental", distrito: "Páramos del Duende-Cerro Plateado (7.679 ha)", complejo: "Duende", generalidades: "Se encuentra ubicado entre los departamentos del Chocó y Valle del Cauca, sobre los 3.450 msnm con una extensión de 1.467 ha.", fauna_flora: "Se caracteriza por tener dos tipos de cobertura vegetal: bosques enanos y bosque andino. Se han identificado murciélagos, oso andino, cuzumbo y tapir de montaña.", datos: "No se han identificado asentamientos humanos"},
    {id: "28", cordillera: "Occidental", distrito: "Páramos del Duende-Cerro Plateado (7.679 ha)", complejo: "Farallones de Cali", generalidades: "Se encuentra ubicado en el departamento de Valle del Cauca, sobre los  3.500-4.040 msnm en un área cercana a las 2.070 ha", fauna_flora: "Se ubica el orobioma de páramo entre las formaciones vegetales de alta montaña, hay asusencia de frailejones.", datos: "No se han identificado asentamientos humanos"},
    {id: "29", cordillera: "Occidental", distrito: "Páramos del Duende-Cerro Plateado (7.679 ha)", complejo: "Cerro Plateado", generalidades: "Se encuentra ubicado entre los departamentos de Cauca y Nariño, sobre los 3.050-3.850 msnm y ocupa alrededor de 4.143 ha", fauna_flora: "Se caracteriza por la presencia de frailejones y por la dominancia de achupalla terrestre", datos: ""},
]

var params = document.querySelectorAll(".group-param"); 

var div = document.createElement("DIV")

function showInfo(data) {
    let datos = "";

    if (data.datos !== "") {
        datos = "<b> Datos: </b> " + data.datos;
    } 

    div.innerHTML = `
        <b> Cordillera: </b> ${data.cordillera} <br><br>
        <b> Distrito: </b> ${data.distrito} <br><br>
        <b> Complejo: </b> ${data.complejo} <br><br>
        <b> Generalidades: </b> ${data.generalidades} <br><br>
        <b> Fauna y Flora: </b> ${data.fauna_flora} <br><br>
        ${datos} 
    `
}

params.forEach(el => {
    el.addEventListener("mouseover", (event) => {
        for (var i=0; i<data.length; i++) {
            if (data[i].id === event.target.id) {
                showInfo(data[i])
            }   
                           
        }   
    })
})

$(function () {
    $('[data-toggle="tooltip"]').tooltip({
        boundary: "viewport",
        template: `
            <div class="tooltip" role="tooltip" style="width: 30%">
                <div class="arrow"></div>
                <div class="tooltip-inner" 
                    style="
                        max-width: none;
                        background:rgb(235, 235, 235); 
                        color:black; 
                        box-shadow: rgb(207, 207, 207) .5px .5px 4px;
                        text-align: left;
                        font-family: verdana;
                        font-size: 12px;                         
                    ">
                </div>
            </div>`,
        title: div
    })
})