const data = [
    {id: "0", humedal: "Sistema Delta Estuario del Río Magdalena", area: "400.000 ha.", ubicacion: "Ciénaga grande de Santa Marta – Departamento del Magdalena.", anio: "1998", descripcion: "Sistema de estuario costero con 20 lagunas de salinidad variable y ríos que atraviesan el área y extensas zonas de manglares. Es importante por su ecosistema de manglares,  el más grande de la región caribe. Sirve como hábitat y zona de reproducción invernal paraespecies de aves, con al menos dos  endémicas; también es un lugar de desove para muchas especies de peces. En la zona también se recolectan mariscos y cangrejos de río, mientras que las zonas más altas se utilizan para la agricultura."},
    {id: "1", humedal: "Laguna del Cocha - IDEM", area: "39.000 ha.", ubicacion: "Departamento de Nariño.", anio: "2001", descripcion: "Es considerado un santuario de vida silvestre. Compuesto  por un lago volcánico y las turberas y bosques andinos circundantes. El sitio sustenta una diversa gama de flora y fauna asociadas, mamíferos como el tapir (Tapirus pinchaque)  y el oso de anteojos (Tremarctos ornatus) en peligro de extinción. Importantes  aves como el somormujo (Podiceps occidentalis), el pato pico dorado (Anas georgica spicauda) y los patos endémicos (Anas cyanoptera borreroi, Oxyura jamaicensis ferruginea). Hay dos importantes especies endémicas de frailejón (Espeletia cochensis, Espeletia schultesiana) y Totora (Scirpus californicus, Juncus bogotensis). El sitio es culturalmente importante ya que los grupos indígenas de la zona, que lo consideran sagrado, lo utilizan para la purificación y la fertilidad."},
    {id: "2", humedal: "Delta del Río San Juan y el Delta del Río Baudó - IDEM", area: "8.888 ha.", ubicacion: "Departamento de Chocó.", anio: "2004", descripcion: "Es formado por márgenes de inundación, playas de arena, ciénagas arbustivas y bosques palustres. La vegetación sobresaliente incluye manglares nativos (Mora oleifera, Mora megistosperma); bosques de manglares (Pelliciera rhizophorae, Avicennia germinans) y cañas gigantes. Entre la fauna destaca la paca moteada (Agouti paca), los pecaríes (Tayassu pecari y Tayassu tajacu), el jaguar (Panthera onca) y la nutria neotropical (Lontra longicaudis). El humedal es hábitat y sitio de reproducción de especies de peces como la Trahira (Hoplias malabaricus) y la lisa (Mugil cephalus. Las amenazas potenciales son la tala de manglares, la sobrepesca, la caza descontrolada, el transporte en botes con motores fuera de borda."},
    {id: "3", humedal: "Sistema Lacustre de Chingaza", area: "4.058 ha. ", ubicacion: "Departamento de Cundinamarca.", anio: "2008", descripcion: "Conjunto de lagunas y humedales que abastecen de agua a la ciudad capital, Bogotá. Ubicada en los Andes del norte de Colombia entre los 3.050 y los 3.950 msnm,  alberga uno de los páramos más húmedos del país y es un centro de particular endemismo que ha sido refugio de más de 400 especies de flora y 500 especies de fauna, algunas de ellas en peligro de extinción y otros que aún no han sido totalmente identificados. Está formado por 20 lagunas de gran importancia para las aves migratorias. Los lagos altoandinos también tienen un gran significado ceremonial precolombino."},
    {id: "4", humedal: "Complejo de Humedales Laguna del Otún", area: "115.883 ha.", ubicacion: "Departamento de Risaralda.", anio: "2008 - ampliación 2017", descripcion: "Un complejo de humedales en Parque Nacional Natural Los Nevados en los Andes Centrales. Incluye lagunas, pantanos, turberas interconectadas o relacionadas funcionalmente entre sí e influenciadas por glaciares y vegetación de páramo. Alberga 52 especies de aves, de las cuales las más vulnerables son las especies acuáticas Oxyura jamaicensis andina y Podiceps occipitalis juninensis, con poblaciones reducidas y distribución muy localizada. Entre las especies de flora importantes que se encuentran en el sitio se encuentran Espeletia hartwegiana centroandina, Podocarpus oleifolius y Polylepis sericea, que también se encuentran bajo protección especial."},
    {id: "5", humedal: "Estrella Fluvial Inírida", area: "250.158,9 ha. ", ubicacion: "Departamentos de Guainía y Vichada.", anio: "2014", descripcion: "Está ubicado en la zona transicional Orinoco - Amazonas y está compuesto principalmente por las zonas de confluencia de los ríos Inírida- Guaviare, Guaviare-Atabapo y Guaviare-Ventuari que se unen al río Orinoco. Esta es una zona única ya que los bosques inundables pertenecen al Bioma Amazónico y los ecosistemas hidrológicos de aguas blancas, negras y transparentes son característicos del río Orinoco. Alberga una gran diversidad especies entre la que se encuentran amenazadas o en peligro como la guacamaya verde oscura (Ara militaris), la nutria (Pteronura brasiliensis) y el oso hormiguero (Myrmecophaga tridactyla) y especies endémicas de la cuenca del Orinoco como Sorubim lima, Pseudoplatystoma metaense y P. orinocoense. También alberga 476 especies de peces (50% de las especies para la cuenca del Orinoco y 34% de las especies del país), 200 especies de mamíferos, 903 de plantas y 324 de aves."},
    {id: "6", humedal: "Complejo de Humedales del Alto Río Cauca Asociado a la Laguna del Sonso", area: "5.524,95 ha.", ubicacion: "Departamento del Valle del Cauca.", anio: "2017", descripcion: "Está compuesto por 24 humedales. Se han identificado treinta y nueve especies de plantas 25 de ellas presentes en la Lista Roja de IUCN con la presencia de 162 especies de aves incluyendo al Buitre de Ciénaga (Anhima cornuta) cuyas poblaciones se encuentran únicamente en Sonso y en la Cienaga del Conchal. Se destaca por su alto nivel de endemismo con cinco especies de peces: Boquiancha (Genycharax tarpon); el Roño (Callichthys fabricioi); el Micudo (Pimelodella macrocephala) y dos Sardinitas, (Hyphessobrycon poecilioides) y (Gephyrocharax caucanus). El sitio es una fuente de alimento y agua para las comunidades, cuyo valor ecológico está amenazado por el crecimiento de la población y la expansión de la frontera agrícola, principalmente la caña de azúcar."},
    {id: "7", humedal: "Lagos de Tarapoto", area: "45.463 ha.", ubicacion: "Departamento del Amazonas.", anio: "2018", descripcion: "El sitio se localiza en el rio Amazonas al sur del país y se compone por varios lagos interconectados entre sí mediante ríos y arroyos. Sustenta especies de plantas y animales como las ceibas (Ceiba pentandra), caimanes negros (Melanosuchus niger), 136 especies de peces, incluyendo el pez de agua dulce más grande que se conoce, el pirarucu (Arapaima gigas), y más de 153 especies de aves. Los delfines grises y rosados (Inia geoffrensis y Sotalia fluviatilis) usan el sitio como hábitat para enseñar a sus crías a pescar. También alberga mamíferos amenazados como el tapir (Tapirus terrestris), el armadillo gigante (Priodontes maximus) y el manatí amazónico (Trichechus inunguis). Esta gran biodiversidad y  sus recursos pesqueros sustentan a las 22 comunidades del resguardo indígena TICOYA (Ticuna, Cocama y Yagua). La designación del Complejo como humedal de importancia internacional se dió tras completar el proceso de consulta y el acuerdo entre autoridades indígenas, nacionales y regionales."},
    {id: "8", humedal: "Sistema Cenagoso de Ayapel", area: "54.000 ha.", ubicacion: "Departamento de Córdoba.", anio: "2018", descripcion: "La ciénaga de Ayapel hace parte del macrosistema de humedales y zonas inundables de la depresión Momposina. Es un sistema de lagunas de la llanura aluvial del río San Jorge. Esta ciénaga cumple una función ambiental importante para la región y el país, pues modera los regímenes hidrológicos de las áreas tributarias de los ríos San Jorge y Cauca, y de varios caños y quebradas que vierten sus caudales sobre ella. Así mismo, alberga una gran variedad de especies de flora y fauna, y brinda refugio, alimento y protección a especies migratorias de peces y aves."},
    {id: "9", humedal: "Complejo Cenagoso de la Zapatosa", area: "123.624 ha.", ubicacion: "Departamento del Cesar.", anio: "2018", descripcion: "La Ciénaga de Zapatosa funciona como amortiguador de las crecientes del río Magdalena. Y además de su importancia ambiental es vital para la seguridad de cientos de personas que viven cerca del río, ya que, si no existiera este importante cuerpo de agua, probablemente las corrientes del Magdalena arrasarían con las poblaciones que se encuentran aguas abajo.  Alberga gran biodiversidad, con cerca de 500 plantas vasculares, 45 especies de peces y 30 de mamíferos, Es el hogar de más de 200 especies de aves, dentro de las que se encuentran nativas y migratorias que llegan de Canadá y de otras partes del mundo a reproducirse y a alimentarse; las más comunes que encontramos en este ecosistema son: la guacharaca caribeña, esmeralda pico rojo, el carpintero costeño, rastrojero y chavarrí."},
    {id: "10", humedal: "Complejo de Humedales de la Cuenca del Río Bita", area: "824.535 ha.", ubicacion: "Departamento del Vichada.", anio: "2018", descripcion: "Es considerado el río mejor conservado del país, mantiendo una integridad ecológica prácticamente primitiva, alimentado por lagunas, morichales y más de 5.000 quebradas y pequeños cauces a lo largo de 710 kilómetros, desde su nacimiento en el municipio de La Primavera, hasta su desembocadura en el río Orinoco. Sorprende por su abrumadora biodiversidad: 424 especies de plantas, 3 de esponjas de agua dulce nunca antes estudiadas en Colombia, 34 de escarabajos coprófagos, al menos 87 de macroinvertebrados acuáticos, 11 de crustáceos decápodos entre camarones y cangrejos, 254 de peces, 19 de anfibios, 38 de reptiles, 201 de aves y 63 de mamíferos."},
    {id: "11", humedal: "Complejo de Humedales Urbanos de Bogotá", area: "667,4 ha.", ubicacion: "Departamento de Cundinamarca.", anio: "2018", descripcion: "Conformado por 11 Parques Ecológicos Distritales de Humedal (PEDH). Estos pantanos permanentes de agua dulce proveen refugio y hábitat a especies endémicas de la región Altoandina  como la Tingua Bogotana (Rallus semiplumbeus) y el Cucarachero de pantano (Cistothorus apolinari). Se registran 196 especies de aves, 42 de ellas son especies acuáticas y 65 corresponden a especies migratorias. Actúa como regulador hídrico de los ríos de la sabana de Bogotá en temporada de lluvias, controlando las inundaciones, y en época seca conservando el nivel freático de los suelos. Constituye el principal conector ecológico del territorio urbano y rural de la cuenca del río Bogotá. Es el primer complejo urbano de Humedales Altoandinos de Latinoamérica designado en el Listado de Humedales de Importancia Internacional. Es considerado un Área Importante para la Conservación de las Aves (ICAS). Entre las principales amenazas para el sitio se encuentran los efectos de la variabilidad climática por precipitación asociados a los fenómenos de El Niño y La Niña."},
]

var humedales = document.querySelectorAll(".group-hum"); 
var div = document.createElement("DIV")

function showInfo(data) {
    div.innerHTML = `
        <b> Humedal: </b> ${data.humedal} <br><br>
        <b> Área Protegida: </b> ${data.area} <br><br>
        <b> Ubicación: </b> ${data.ubicacion} <br><br>
        <b> Año Declaración: </b> ${data.anio} <br><br>
        <b> Descripción: </b> ${data.descripcion}
    `
}

humedales.forEach(el => {
    el.addEventListener("mouseover", (event) => {
        console.log(event)
        for (var i=0; i<data.length; i++) {
            if (data[i].id === event.target.id) {
                showInfo(data[i])
            }   
                           
        }   
    })
})

$(function () {
    $('[data-toggle="tooltip"]').tooltip({
        boundary: "viewport",
        template: `
            <div class="tooltip" role="tooltip" style="width: 33%">
                <div class="arrow"></div>
                <div class="tooltip-inner" 
                    style="
                        max-width: none;
                        background:rgb(235, 235, 235); 
                        color:black; 
                        box-shadow: rgb(207, 207, 207) .5px .5px 4px;
                        text-align: left;
                        font-family: verdana;
                        font-size: 12px;                         
                    ">
                </div>
            </div>`,
        title: div,
    })
})