const data = [
    {id: "0", DRMI: "Agualinda", area: "326,75 ha.", ubicacion: "Departamento de Risaralda.", autoridad: "Corporación Autónoma Regional de Risaralda (CARDER)", acuerdo: "Acuerdo No 013 del 17 de junio de 2011 \'Por el cual se declara, reserva y alindera el Distrito de Manejo Integrado Agualinda como categoría de área protegida integrante del SINAP\'"},
    {id: "1", DRMI: "Alto de Ventanas", area: "23538,00 ha.", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Acto Administrativo Acuerdo 180-ACU1804-528 \'Por medio del cual se declara, reserva, delimita y alindera el Área protegida Distrito Regional de Manejo Integrado Alto de Ventanas\'"},
    {id: "2", DRMI: "Alto del Insor", area: "6900,00 ha.", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación para el Desarrollo Sostenible de Urabá (CORPOURABÁ)", acuerdo: "Resolución 010 del 17 de diciembre de 2009 \'Por medio del cual se declara el Distrito de Manejo Integrado Alto del Insor y su área de influencia y se adopta el Plan de Manejo, en los Municipios de Cañasgordas, Giraldo y Abriaquí, Departamento de Antioquia, y se adoptan otras disposiciones\'"},
    {id: "3", DRMI: "Angula Alta - Humedal El Pantano", area: "3635,00 ha.", ubicacion: "Departamento de Santander.", autoridad: "Corporación Autónoma Regional para la Defensa de la Meseta de Bucaramanga (CDMB)", acuerdo: "Acuerdo 1139 del 25 de febrero de 2009, por medio del cual se declara el Distrito de Manejo Integrado en la Angula Alta - Humedal el Pantano, localizado en los municipios de Giròn y Lebrija en el Departamento de Santander"},
    {id: "4", DRMI: "Arrayanal", area: "1191,83  ha.", ubicacion: "Departamento de Risaralda.", autoridad: "Corporación Autónoma Regional de Risaralda (CARDER)", acuerdo: "Acuerdo No 016 del 17 de junio de 2011 \'Por el cual se declara, reserva y alindera el Distrito de Manejo Integrado Arrayanal como categoría de área protegida integrante del SINAP\'"},
    {id: "5", DRMI: "Bañaderos Cuenca Alta del Río Camarones", area: "10820,20 ha.", ubicacion: "Departamentos de La Guajira.", autoridad: "Corporación Autónoma Regional de la Guajira (CORPOGUAJIRA)", acuerdo: "Resolución 012 del 03 de octubre de 2013 \'POR EL CUAL SE DECLARA EL DISTRITO DE MANEJO INTEGRADO BAÑADEROS- CUENCA ALTA DEL RÍO CAMARONES, UBICADO EN JURISDICCIÓN DE LOS MUNICIPIOS DE RIOHACHA, HATONUEVO, BARRANCAS, Y DISTRACCIÓN, DEPARTAMENTO DE LA GUAJIRA Y SE ADOPTAN OTRAS MEDIDAS PARA SU ADMINISTRACIÓN Y MANEJO\'"},
    {id: "6", DRMI: "Banco Totumo Bijibana", area: "1528,90 ha.", ubicacion: "Departamento del Atlántico.", autoridad: "Corporación Autónoma Regional del Atlántico (CRA)", acuerdo: "Articulo 35 del Acuerdo No.004 del 13 de marzo de 2017 de la Asamblea corporativa de la CRA, declara como Distrito Regional de Manejo Integrado Banco Totumo Bijibana, ubicado en la jurisdicciòn de la Corporaciòn Autonoma Regional del Atlàntico CRA."},
    {id: "7", DRMI: "Bosque Seco Tropical Pozo Azul", area: "5067,11 ha.", ubicacion: "Departamento de Norte de Santander.", autoridad: "Corporación Autónoma Regional de la Frontera Nororiental (CORPONOR)", acuerdo: "Resolución 043 de 20 de diciembre de 2019 \'por el cual se declara, reserva, delimita y alindera el Distrito Regional de Manejo Integrado (DRMI) Bosque Seco Tropical Sur Pozo Azul, en los municipios de Cúcuta y San Cayetano, departamento de Norte de Santander y se dictan otras disposiciones\'"},
    {id: "8", DRMI: "Bosque Seco de la Vertiente Oriental del río Magdalena", area: "36126,93 ha.", ubicacion: "Departamento de Cundinamarca.", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 20 del 17 julio de 2018 \'Por medio del cual se declara, delimita y alindera el Distrito Regional de Manejo Integrado Bosque Seco de la Vertiente Oriental del río Magdalena, ubicado en la jurisdicción de la Corporación Autónoma Regional de Cundinamarca - CAR, y se dictan normas para su administración y manejo sostenible\'"},
    {id: "9", DRMI: "Bosque Seco del Occidente Antioqueño", area: "70166,87 ha.", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Resolución 626 del 23 de diciembre de 2021 \'Por Medio Del Cual Se Declara, Reserva, Delimita Y Alindera El Área Protegida Distrito Regional De Manejo Integrado Bosque Seco Del Occidente Antioqueño Y Se Modifica El Acuerdo 017 De 1996\'"},
    {id: "10", DRMI: "Bosques, Mármoles y Pantágoras", area: "15905,90 ha.", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "Resolución 395 de 26 de Septiembre de 2019 \'El Área Protegida a declarada se caracteriza por ser proveedor de servicios ecosistémicos y el más importante es el recurso hídrico, por el alto número de fuentes hídricas que alberga, abasteciendo acueductos municipales, veredales y para el desarrollo de las diferentes actividades económicas que se realizan en el área; además de poseer ecosistemas estratégicos como bosques húmedos asociados al complejo kárstico, cavernas con importancia arqueológica y una gran biodiversidad (flora y fauna). Ecosistema único en el departamento de Antioquia\'"},
    {id: "11", DRMI: "Bucaramanga", area: "4834,70 ha.", ubicacion: "Departamento de Santander.", autoridad: "Corporación Autónoma Regional para la Defensa de la Meseta de Bucaramanga (CDMB)", acuerdo: "Resolución 839 del 23 de diciembre de 1996 \'Por el cual se declara un Distrito de Manejo Integrado\'... El Consejo Directivo CDMB en uso de sus facultades legales y estatutarias y en especial las conferidas por la ley 99 de 1993 y el Decreto 1974 de 1989 y considerando: ..."},
    {id: "12", DRMI: "Cacica Noría", area: "5200,60 ha.", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Acuerdo 480 del 29 de noviembre de 2016, por medio del cual se declara, reserva, delimita y alindera un área de 5.200,6 hectáreas, como Distrito Regional de Manejo Integrado Cacica Noría, en jurisdicción del Municipio de Anorí, departamento de Antioquia."},
    {id: "13", DRMI: "Camelias", area: "12718,26 ha.", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "ACUERDO Nro. 328 Del 1 de julio de 2015. Por medio del cual se declara el Distrito Regional de Manejo Integrado Las Camelias, sobre áreas identificadas como zonas excluibles de la minería en virtud del Décreto 1374 de 2013 y se dictan otras disposiciones."},
    {id: "14", DRMI: "Cañon del Rio Alicante", area: "6292,00 ha.", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Resolución 233 del 12 de octubre de 2006 \'Por medio del cual se declara, reserva y delimita como Distrito de Manejo Integrado de los Recursos Naturales el Cañón del Río Alicante y se toman otras decisiones\'"},
    {id: "15", DRMI: "Carimagua", area: "15123,62 ha", ubicacion: "Departamento del Meta.", autoridad: "Corporación para el Desarrollo Sostenible del Area de Manejo Especial La Macarena (CORMACARENA)", acuerdo: "Resolución 09 del 02 de octubre de 2015 La declaratoria del Distrito Regional de Manejo Integrado de Carimagua - DRMI - se articula al Plan de Gestión Ambiental Regional - PGAR 2010-2019 dentro de la línea estratégica No. 2 denominada \'Conservación, protección y restauración del patrimonio natural y la biodiversidad\'"},
    {id: "16", DRMI: "Cerro Banderas Ojo Blanco", area: "22073,79 ha", ubicacion: "Departamento del Huila.", autoridad: "Corporación Autónoma Regional del Alto Magdalena (CAM)", acuerdo: "Resolución 012 del 27 de septiembre del 2007 \'POR EL CUAL SE DECLARAN LAS AREAS NATURALES CERRO BANDERAS - OJO BLANCO COMO PARQUE NATURAL REGIONAL Y SE DICTAN NORMAS PARA SU ADMINISTRACION Y MANEJO SOSTENIBLE\'"},
    {id: "17", DRMI: "Cerro Chimayoy", area: "3127,00 ha", ubicacion: "Departamento de Nariño.", autoridad: "Corporación Autónoma Regional de Nariño (CORPONARIÑO)", acuerdo: "Acuerdo 015 del 17 de diciembre de 2019, Por el cual se declara como Distrito Regional de Manejo Integrado (DRMI) Cerro Chimayoy. El Consejo directivo de la Corporación Autónoma Regional de Nariño CORPONARIÑO en uso de sus facultades constitucionales, legales, estatutarias y en especial las conferidas en los artículos 27 (literal g) y 31 (numeral 16) de la ley 99 de 1993, el artículo 2.2.2.1.2.4, Decreto 1076 de 2015 y demás normas vigentes y concordantes."},
    {id: "18", DRMI: "Cerro El Tabor", area: "1159,76 ha", ubicacion: "Departamento de Cundinamarca.", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 038 del 18 de octubre de 2005 \'Por el cual se declara y alindera la Reserva Forestal Protectora - Productora Cerro El Tabor ACUERDA Artículo primero: Declarar como zona de Reserva Forestal Protectora-Productora una zona de 1.159,76 hectáreas, en jurisdicción de los municipios de San Juan de Rio Seco, Pulí y Beltrán, departamento de Cundinamarca.\'"},
    {id: "19", DRMI: "Cerro Guadalupe", area: "1608,00 ha", ubicacion: "Departamento de Caldas.", autoridad: "Corporación Autónoma Regional de Caldas (CORPOCALDAS)", acuerdo: "Acuerdo 25 de 2017 (3 octubre) Por medio del cual se reserva, delimita, alindera y declara el Distrito Regional de Manejo Integrado Cerro Guadalupe. El Consejo Directivo de la Corporación Autónoma Regional de Caldas ?CORPOCALDAS, en uso de sus atribuciones, en especial las que le confiereconfieren el literal g) del artículo 27, en concordancia con el numeral 16 del artículo 31, de la Ley 99 de 1993"},
    {id: "20", DRMI: "Cerro de Juaica", area: "883,00 ha", ubicacion: "Departamento de Cundinamarca.", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 42 del 03 de diciembre de 1999 \'Por el cual se declara y alindera un Distrito de Manejo Integrado de los Recursos Naturales Renovables en el “Cerro de Juaica” municipio de Tenjo\'"},
    {id: "21", DRMI: "Cerros de San Nicolás", area: "3506,94 ha", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "ACUERDO Nro. 323 Del 1 de julio de 2015 Por medio del cual se declara el Distrito Regional de Manejo Integrado Cerros de San Nicolás, sobre áreas identificadas como zonas excluibles de la minería en virtud del Decreto 1374 de 2013 y se dictan otras disposiciones."},
    {id: "22", DRMI: "Chili Bosque Alto Andino Pijao", area: "6192,70 ha", ubicacion: "Departamento de Quindío.", autoridad: "Corporación Autónoma Regional del Quindío (CRQ)", acuerdo: "Resolución 13 del 23 de diciembre de 2015 \'Acuerdo por medio del cual se declara el Distrito Regional de Manejo Integrado Chili Bosque Alto Andino Pijao, con un área aproximada de 6192,70 hectáreas, localizado del Municipio de Pijao, Quindío\'"},
    {id: "23", DRMI: "Chinchorro", area: "1800,30 ha", ubicacion: "Departamento de Cundinamarca.", autoridad: "Corporación Autónoma Regional del Guavio (CORPOGUAVIO)", acuerdo: "Acuerdo 019 de 2015, por medio del cual se declara y alindera el área protegida denominada \'DISTRITO REGIONAL DE MANEJO INTEGRADO CHINCHORRO\' ubicado en las veredas Palenque I, Palenque II, Guavio, La Unión y Santuario del municipio de Gama, Cundinamarca, en área aproximada de MIL SETECIENTAS VEINTICUATRO PUNTO OCHO HECTÁREAS (1724,8)."},
    {id: "24", DRMI: "Ciénaga de Barbacoas", area: "32074,00 ha", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Acuerdo del Consejo Directivo No. 180-ACU1705-493 \'Por medio del cual se declara, reserva, delimita y alindera el área protegida Distrito Regional de Manejo Integrado Cienaga de Barbacoas\'"},
    {id: "25", DRMI: "Ciénaga de Chiqueros", area: "6764,94  ha", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "ACTO ADMINISTRATIVO: 180-ACU1808-543 \'Por medio del cual de declara, reserva, delimita y alindera el área protegida Distrito Regional de Manejo Integrado Ciénaga de Chiqueros\'"},
    {id: "26", DRMI: "Ciénagas Corrales y El Ocho", area: "12865,30 ha", ubicacion: "Departamento de Antioquia y Bolivar", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Acuerdo 576 del 10 de diciembre de 2019 del Consejo Directivo de CORANTIOQUIA, \'Por medio del cual se declara, reserva, delimita y alindera el área protegida Distrito Regional de Manejo Integrado Ciénagas Corrales y El Ocho\'"},
    {id: "27", DRMI: "Ciénagas El Sapo y Hoyo Grande", area: "12227,20 ha", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Resolución 508 del 26 d octubre de 2017 \'Por medio del cual se declara, reserva, delimita y alindera el área protegida Distrito Regional de Manejo Integrado Ciénagas El Sapo y Hoyo Grande\'"},
    {id: "28", DRMI: "Complejo Cenagoso de Zapatosa", area: "140765,70 ha", ubicacion: "Departamento de Cesar y Magdalena.", autoridad: "\n > Corporación Autónoma Regional del Cesar (CORPOCESAR). \n > Corporación Autónoma Regional del Magdalena (CORPAMAG).", acuerdo: "Acuerdo de Comisión Conjunta No. 001. CORPOCESAR - CORPAMAG POR LA CUAL SE DELIMITA, RESERVA Y DECLARA EL DISTRITO REGIONAL DE MANEJO INTEGRADO COMPLEJO CENAGOSO DE ZAPATOSA CCZ en los municipios de Chimichagua, Tamalameque, Curumaní y Chiriguaná en el departamento del Cesar y El Banco en el departamento del Magdalena, en jurisdicción de la Corporación Autónoma Regional del Cesar - CORPOCESAR y la Corporación Autónoma Regional del Magdalena."},
    {id: "29", DRMI: "Complejo Cenagoso de Zarate Malibú y Veladero", area: "63992,00 ha", ubicacion: "Departamento de Magdalena.", autoridad: "Corporación Autónoma Regional del Magdalena (CORPAMAG)", acuerdo: "Resolución 10 del 27 de julio de 2007 Por el cual se declara el complejo Cenagoso de Zarate , malibu y Veladero en jurisdicción de Municipios de Plato y Santa Barbara de pinto como un distrito de manejo integrado de recursos naturales"},
    {id: "30", DRMI: "Complejo Cenagoso del Bajo Sinú", area: "42013,00 ha", ubicacion: "Departamento de Córdoba.", autoridad: "Corporación Autónoma Regional de los Valles del Sinú y San Jorge (CVS)", acuerdo: "Resolución 76 del 25 de octubre 2007 Por medio del cual se declara el Distrito de Manejo Integrado delos recursos naturales DMI del área de reserva del Complejo Cenagóso del Bajo Sinú"},
    {id: "31", DRMI: "Complejo Ciénagas Papayal", area: "2838,50 ha", ubicacion: "Departamento de Santander.", autoridad: "Corporación Autónoma Regional para la Defensa de la Meseta de Bucaramanga (CDMB)", acuerdo: "Resolución 1193 del 10 de diciembre de 2010 Por el cual se declara un \'DISTRITO REGIONAL DE MANEJO INTEGRADO DMI Complejo Ciénagas Papayal\' localizado en el municipio de Rionegro en el departamento de Santander, se definen las categorías de ordenamiento territorial, se reglamentan los usos de los suelos y se establecen normas y directrices para el manejo, conservación y aprovechamiento sostenible de los recursos naturales renovables y se establece el Plan de manejo para el control de las actividades económicas que en el área se desarrollan."},
    {id: "32", DRMI: "Complejo Lagunar de Fúquene, Cucunubà y Palacio", area: "19194,00 ha", ubicacion: "Departamento de Cundinamarca.", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 18 del 11 de julio de 2017 Por medio del cual de declara como Distrito Regional de Manejo Integrado (DMI)el \'Complejo Lagunar Fùquene, Cucunubà y Palacio\' ubicado en la jurisdicción de la Corporación Autónoma Regional de Cundinamarca-CAR."},
    {id: "33", DRMI: "Cristalina la Mesa", area: "2251,83 ha", ubicacion: "Departamento de Risaralda.", autoridad: "Corporación Autónoma Regional de Risaralda (CARDER)", acuerdo: "Acuerdo No 024 de 17 de junio de 2011 \'Por el cual se declara, reserva y alindera el Distrito de Manejo Integrado Cristalina La Mesa como categoría de área protegida integrante del SINAP\'"},
    {id: "34", DRMI: "Cuchilla Cerro Plateado Alto San Jose", area: "8900,00 ha", ubicacion: "Departamento de Antioquia y Chocó", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Resolución 244 del 20 de diciembre de 2006 Por medio del cual se declara, reserva y delimita como Distrito de Manejo Integrado de los Recursos Naturales Cuchilla Cerro Plateado-Alto San José y se toman otras decisiones"},
    {id: "35", DRMI: "Cuchilla Del San Juan", area: "11048,80 ha", ubicacion: "Departamento de Boyacá.", autoridad: "Corporación Autónoma Regional de Risaralda (CARDER)", acuerdo: "ACUERDO DEL CONSEJO DIRECTIVO No. 04 POR EL CUAL SE CREA EL PARQUE REGIONAL NATURAL LA CUCHILLA DE SAN JUAN El Consejo Directivo de la Corporación Autónoma Regional de Risaralda, en uso de sus atribuciones, en especial las que le confieren los literales g) e i) del artículo 23 de la Resolución 1480 de 1995, proferida por el Ministerio del Medio Ambiente."},
    {id: "36", DRMI: "Cuchilla El Varal", area: "3390,56 ha", ubicacion: "Departamento de Risaralda.", autoridad: "Corporación Autónoma Regional de Chivor (CORPOCHIVOR)", acuerdo: "Resolución 3 del 30 de enero de 2019 Por medio del cual se declara, reserva, delimita y alindera Distrito Regional de Manejo Integrado (DRMI) Cuchilla El Varal, en los municipios de Garagoa y Macanal, en jurisdicción de la Corporación Autónoma Regional de Chivor CORPOCHIVOR"},
    {id: "37", DRMI: "Cuchilla Jardin Tamesis", area: "28061,00 ha", ubicacion: "Departamento de Antioquia y Caldas.", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Resolución 316 del 22 de abril de 2009 Por medio del cual se declara, reserva y alindera como Distrito de Manejo Integrado de los Recursos Naturales renovables la denominada Cuchilla Jardín Támesis"},
    {id: "38", DRMI: "Cuchilla Mesa Alta", area: "685,89 ha", ubicacion: "Departamento de Boyacá.", autoridad: "Corporación Autónoma Regional de Chivor (CORPOCHIVOR)", acuerdo: "Resolución 025 del 18 de diciembre 2019 por medio del cual se declara, reserva, delimita y alindera el Distrito Regional de Manejo Integrado (DRMI) cuchilla Mesa Alta, en los municipios de Tibana y Nuevo Colon en jurisdiccion de la Corporacion Autonoma Regional de Chivor CORPOCHIVOR"},
    {id: "39", DRMI: "Cuchilla San Cayetano", area: "8993,60 ha", ubicacion: "Departamento de Boyacá y Cundinamarca", autoridad: "Corporación Autónoma Regional de Chivor (CORPOCHIVOR)", acuerdo: "Resolución 9 del 28 de junio de 2017 \'Por medio del cual se declara, reserva, delimita y alindera Distrito Regional de Manejo Integrado (DRMI) Cuchilla San Cayetano, en los municipios de Chivor, Almeida, Somondoco, Guayatá, en jurisdicción de la Corporación Autónoma Regional de Chivor CORPOCHIVOR\'"},
    {id: "40", DRMI: "Cuchilla de Bellavista", area: "1302,00 ha", ubicacion: "Departamento de Caldas y Tolima", autoridad: "Corporación Autónoma Regional de Caldas (CORPOCALDAS)", acuerdo: "Resolución 32 del 14 de diciembre de 2010 Por medio del cual se delimita y declara el distrito de Manejo Integrado de Recursos Naturales Renovables \'Cuchilla de Bellavista\' y se dictan normas para su uso y funcionamiento."},
    {id: "41", DRMI: "Cuchilla de Peñas Blancas y del Subia", area: "5985,71 ha", ubicacion: "Departamento de Cundinamarca", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 026 del 24 de noviembre de 1993 \'Por el cual se declara y alinda un Distrito de Manejo Integrado de Recursos naturales renovable\' ACUERDA: ARTÍCULO PRIMERO. Declarar como Distrito de Manejo Integrado los terreno ubicados dentro de los globos 1, 2 y 3 localizados en la Cuchilla conocida con los nombres de Peñas Blancas y del Subia en los municipios de San Antonio del Teguendama, El Colegio y Viotá en el departamento de Cundinamarca."},
    {id: "42", DRMI: "Cuchilla de San Antonio", area: "13581,95 ha", ubicacion: "Departamento de Cundinamarca", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 23 del 18 de noviembre de 2008 Por el cual se declara como Distrito de Manejo Integrado (DMI) a un sector que conforma la “Cuchilla de San Antonio”, en el municipio de Puerto Salgar en el departamento de Cundinamarca y se toman otras determinaciones” Acuerda: ARTÍCULO PRIMERO: Declarar como Distrito de Manejo integrado de los Recursos Naturales Renovables (DMI) el sector integrado por los terrenos que conforman la Cuchilla de San Antonio en jurisdicción del municipio de Puerto Salgar en el departamento de Cundinamarca."},
    {id: "43", DRMI: "Cuchilla el Chuscal", area: "2335,00 ha", ubicacion: "Departamento de Cundinamarca", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 18 del 07 de octubre de 1998, Por el Cual se declara y alindera un Distrito de Manejo Integrado de los Recursos Naturales Renovables los terrenos que conforman las partes altas de los rios San Juan, Gualivá y Sabaneta en jurisdicción del municipio de la Vega en el Departamento de Cundinamarca el DRMI de la Cuchilla el Chuscal"},
    {id: "44", DRMI: "Cuchilla los Cedros", area: "2063,70 ha", ubicacion: "Departamento de Antioquia.", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "ACUERDO Nro. 329 Del 1 de julio de 2015 Por medio del cual se declara el Distrito Regional de Manejó Integrado Cuchilla Los Cedros, sobre áreas identificadas como zonas excluibles de la minería en virtud del Decreto 1374 de 2013 y se dictan otras disposiciones."},
    {id: "45", DRMI: "Cuchillas Negra y Guanaque", area: "19304,60 ha", ubicacion: "Departamento de Boyacá y Cundinamarca", autoridad: "Corporación Autónoma Regional de Chivor (CORPOCHIVOR)", acuerdo: "Resolución 20 del 26 de noviembre de 2014 Por el cual se declara, reserva, delimita y alindera el Distrito Regional de Manejo Integrado (DRMI) Cuchillas Negra y Guanaque, en los municipios de Santa María, Chivor, Macanal y Campohermoso, en jurisdicción de la Corporación Autónoma Regional de Chivor - CORPOCHIVOR."},
    {id: "46", DRMI: "Cuenca Alta del Río Atrato", area: "17968,00 ha", ubicacion: "Departamento de Chocó y Antioquia", autoridad: "Corporación Autónoma Regional para el Desarrollo Sostenible del Chocó (CODECHOCÓ)", acuerdo: "Acuerdo 011 del 22 de diciembre de 2016, por medio del cual se declara el Distrito Regional de Manejo Integrado Cuenca Alta del Rìo Atrato, con una superficie de 17.968 hectáreas."},
    {id: "47", DRMI: "Cuenca baja del Río Ranchería", area: "32443,13 ha", ubicacion: "Departamento de La Guajira", autoridad: "Corporación Autónoma Regional de la Guajira (CORPOGUAJIRA)", acuerdo: "Resolución 020 del 19 de diciembre de 2014 Por el cual se declara el Distrito de Manejo Integrado de la Cuenca Baja del Rio Rancheria, ubicado en jurisdicción de los municipios de Riohacha, Manaure, Maicao y Albania, Departamento de La Guajira y se adoptan otras medidas para su administración y manejo sostenible."},
    {id: "48", DRMI: "Cuervos", area: "501,60 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "ACUERDO Nro. 325 Del 1 de julio de 2015 Por medio del cual se declara el Distrito Regional de Manejo Integrado Cuervos, sobre áreas identificadas como zonas excluibles de la minería en virtud del Decreto 1374 de 2013 y se dictan otras disposiciones."},
    {id: "49", DRMI: "De la Cuenca Alta del Río Quindío de Salento", area: "32722,30 ha", ubicacion: "Departamento de Quindío, Tolima y Risaralda.", autoridad: "Corporación Autónoma Regional del Quindío (CRQ)", acuerdo: "ACUERDO 010 (Diciembre 17 de 1998) \'Por medio del cual se declara la Cuenca Alta del Río Quindío Distrito de Manejo Integrado de los Recursos Naturales Renovables y se dictan otras disposiciones\'"},
    {id: "50", DRMI: "Del Complejo de Humedales de Ayapel", area: "145512,52 ha", ubicacion: "Departamento de Córdoba, Antioquia y Bolivar", autoridad: "Corporación Autónoma Regional de los Valles del Sinú y San Jorge (CVS)", acuerdo: "Resolución 133 del 16 de diciembre de 2009 Por medio del cual se declara el Distrito de Manejo Integrado de los recursos naturales DMI del complejo de humedales de Ayapel"},
    {id: "51", DRMI: "Del Humedal San Silvestre", area: "69954,71 ha", ubicacion: "Departamento de Santander", autoridad: "Corporación Autónoma Regional de Santander (CAS)", acuerdo: "Resolución 0058 del 27 de noviembre de 2006 \'Por el cual se declara y alindera un Distrito de Manejo Integrado de recursos naturales renovables (DMI) Humedal de San Silvestre en los municipios de Barrancabermeja y San Vicente de Chucuri en el Departamento de Santander, ... y\'"},
    {id: "52", DRMI: "Del Rio Minero y sus Zonas Aledañas", area: "48394,48 ha", ubicacion: "Departamento de Santander y Boyacá", autoridad: "Corporación Autónoma Regional de Santander (CAS)", acuerdo: "Resolución 117 del 29 de julio de 2009 Por el cual se declara y alindera el Distrito de manejo Integrado de los Recursos Naturales Renovables - DMI del Río Minero y sus zonas aledañas, localizado en los municipios de Bolivar, Cimitarra, El peñon, La Belleza y Sucre, Departamento de Santander."},
    {id: "53", DRMI: "Delta del Río Ranchería", area: "3601,00 ha", ubicacion: "Departamento de La Guajira", autoridad: "Corporación Autónoma Regional de la Guajira (CORPOGUAJIRA)", acuerdo: "Resolución 015 del 13 de noviembre de 2014 Por el cual se declara el Distrito de Manejo Integrado del Delta del Rio Rancheria, ubicado en jurisdicción de los municipios de Riohacha y Manaure, Departamento de La Guajira y se adoptan otras medidas para su administración y manejo sostenible."},
    {id: "54", DRMI: "Divisoria Valle de Aburra Rio Cauca", area: "28075,00 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Resolución 267 del 10 de septimbre de 2007 Por medio del cual se declara, reserva y delimita como Distrito de Manejo Integrado de los Recursos Naturales Renovables la ladera occidental del Valle de Aburrá Río Cauca y se toman otras decisiones."},
    {id: "55", DRMI: "Ecosistema de Manglar y Lagunar Ciénaga de la Caimanera", area: "2125,00 ha", ubicacion: "Departamento de Sucre", autoridad: "Corporación Autónoma Regional de Sucre (CARSUCRE)", acuerdo: "Resolución 011 del 01 de septiembre de 2008 Por el cual se declara el Distrito de manejo Integrado del Sistema de Manglar y Lagunar de la Ciénaga de la Caimanera, Municipio de Santiago de Tolú, Departamento de Sucre."},
    {id: "56", DRMI: "Ecosistema de Sabanas Abiertas y Arbustivas y Sistemas Asociados en el Municipio de Galeras", area: "1577,70 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional de Sucre (CARSUCRE)", acuerdo: "Resolución 007 del 22 de diciembre de 2010 POR EL CUAL SE DECLARA COMO DISTRITO REGIONAL DE MANEJO INTEGRADO (DRMI) EL ECOSISTEMA DE SABANAS ABIERTAS Y ARBUSTIVAS Y SISTEMAS ASOCIADOS EN EL CORREGIMIENTO DE BARAYA, MUNICIPIO DE GALERAS,DPTO DE SUCRE"},
    {id: "57", DRMI: "El Aburrido", area: "1104,43 ha", ubicacion: "Departamento de Santander", autoridad: "Corporación Autónoma Regional para la Defensa de la Meseta de Bucaramanga (CDMB)", acuerdo: "Resolución 1421 del 17 de diciembre de 2021 Por medio del cual se reserva, delimita, alindera y declara el “DISTRITO REGIONAL DE MANEJO INTEGRADO DRMI “EL ABURRIDO” en jurisdicción de los municipios de Bucaramanga, Rionegro y Matanza, se adopta el Plan de Manejo y se acuerdan otras disposiciones."},
    {id: "58", DRMI: "El Bocachico", area: "1392,00 ha", ubicacion: "Departamento de Casanare", autoridad: "Corporación Autónoma Regional de la Orinoquía (CORPORINOQUIA)", acuerdo: "ACUERDO No.1100.02.2.13.014 DE 16 DE DICIEMBRE DE 2013 POR MEDIO DEL CUAL SE DECLARA RESERVA Y DECLARA EL DISTRITO REGIONAL DE MANEJO INTEGRADO EL \'BOCACHICO\' UBICADO EN LA VEREDA GAVIOTAS JURISDICCIÓN DEL MUNICIPIO DE MANÍ DEPARTAMENTO DE CASANARE EL CONSEJO DIRECTIVO DE LA CORPORACIÓN AUTÓNOMA REGIONAL DE LA ORINOQUIA CORPORINOQUIA, EN USO DE SUS FACULTADES LEGALES Y REGLAMENTARIAS, EN ESPECIAL LO DISPUESTO EN EL PARÁGRAFO DEL ARTÍCULO 40 DEL DECRETO REGLAMENTARIO 2372 DE 2010"},
    {id: "59", DRMI: "El Capiro", area: "471,92 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "ACUERDO Nro. 326 Del 1 de julio de 2015 Por medio del cual se declara el Distrito Regional de Manejo Integrado El Capiro, sobre áreas identificadas como zonas excluibles de la minería en virtud del Decreto 1374 de 2013 y se dictan otras disposiciones."},
    {id: "60", DRMI: "El Chilcal", area: "911,70 ha", ubicacion: "Departamento de Valle del Cauca", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Resolución 73 del 15 de septiembre de 2015 Por el cual se declara el Distrito Regional de Manejo Integrado El Chilcal, ubicado en el municipio de Dagua, se adopta su plan de manejo y se dictan otras determinaciones."},
    {id: "61", DRMI: "El Meandro o Madrevieja de Guarinocito", area: "75,00 ha", ubicacion: "Departamento de Caldas", autoridad: "Corporación Autónoma Regional de Caldas (CORPOCALDAS)", acuerdo: "Resolución 0068 04 de octubre de 1988 La Junta Directiva del instituto nacional de los recursos naturales renovables y del ambiente acuerdan declarar como Distrito de manejo integrado Meandro o madrevieja de Guarinocito"},
    {id: "62", DRMI: "El Tinije", area: "13768,00 ha", ubicacion: "Departamento de Casanare", autoridad: "Corporación Autónoma Regional de la Orinoquía (CORPORINOQUIA)", acuerdo: "Resolución 08012 del 05 de diciembre de 2008 \'Por medio del cual se declara y se delimita como Distrito de Manejo Integrado de los Recursos Naturales Renovables (D.M.I) de \'El Caño y la Laguna del Tinije\' y se adoptan otras determinaciones."},
    {id: "63", DRMI: "Embalse el Peñol y Cuenca Alta del Río Guatapé", area: "18385,98 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "Acuerdo No. 010 DE ENERO 28/85 DE LA Junta Directiva del Instituto Nacional de los Recursos Naturales Renovables y del Ambiente INDERENA, en el cual se declara Distrito de Manejo Integrado y área de recreación una zona denomina Embalse de El Peñol y Cuenca Alta del Río Guatapé en jurisdicción de los Municipios de El Peñol, Guatapé San Rafael, Departamento de Antioquia"},
    {id: "64", DRMI: "En el Territorio Colectivo del Consejo Comunitario de la Comunidad Negra de la Plata", area: "6791,00 ha", ubicacion: "Departamento del Valle del Cauca.", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Resolución 56 del 18 de agosto de 2008 Por el cual se declara el distrito regional de manejo integrado de los recursos naturales en el territorio colectivo del consejo comunitario de la comunidad negra de la Plata Bahía Málaga municipio de Buenaventura."},
    {id: "65", DRMI: "Encanto de los Manglares del Bajo Baudó", area: "\n > 106836,00 ha terrestres. \n > 207726,00 ha marítina.", ubicacion: "Departamento del Chocó", autoridad: "Corporación Autónoma Regional para el Desarrollo Sostenible del Chocó (CODECHOCÓ)", acuerdo: "Acuerdo 008 de 2017, por medio del cual se Reserva, delimita, alindera, declara y administra como · \'Distrito Regional de Manejo Integrado Encanto de los Manglares del Bajo Baudó\' con una superficie total de trescientos catorce mil quinientos sesenta y dos (314.562) hectáreas, localizada en el municipio del Bajo Baudó, departamento del Chocó, al norte del municipio del Litoral del San Juan y al sur del municipio de Nuqui."},
    {id: "66", DRMI: "Enclave Subxerofitico de Atuncela", area: "1011,50 ha", ubicacion: "Departamento del Valle del Cauca.", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Acuerdo 64 del 13 de diciembre de 2007, Por el cual se declara el enclave subxerofitico de atuncela como un Distrito de manejo integrado de los recursos naturales renovables"},
    {id: "67", DRMI: "Ensenada de Rionegro, los Bajos Aledaños, las Ciénagas de Marimonda y el Salado", area: "\n > 25735,00 ha terrestre. \n > 5025,00 ha marítima.", ubicacion: "Departamento de Anitoquia.", autoridad: "Corporación para el Desarrollo Sostenible de Urabá (CORPOURABÁ)", acuerdo: "Resolución 012 del 17 de diciembre de 2009 Por el cual se declara el Distrito de Manejo Integrado ? (DMI) Ensenada de Rionegro, los Bajos Aledaños, las Ciénagas de Marimonda y el Salado en el Municipio de Necoclí, Departamento de Antioquia, se adopta el Plan de Manejo Ambiental y se adoptan otras disposiciones."},
    {id: "68", DRMI: "Golfo de Tribugá Cabo Corrientes", area: "60138,60 ha marítima", ubicacion: "Departamento del Chocó", autoridad: "Corporación Autónoma Regional para el Desarrollo Sostenible del Chocó (CODECHOCÓ)", acuerdo: "Acuerdo 011 del 18 de Diciembre de 2014, por medio del cual se declara el Distrito Regional de Manejo Integrado Golfo de Tribugá Cabo Corrientes en el municipio de Nuqui - Departamento del Chocó, y se adoptan otras determinaciones."},
    {id: "69", DRMI: "Guacas", area: "4378,10 ha", ubicacion: "Departamento del Valle del Cauca.", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Acuerdo 079 del 12 de diciembre de 2016, por medio del cual se declara el Distrito Regional de Manejo Integrado Guacas, ubicado en el municipio de Bolivar, Departamento del Valle del Cauca."},
    {id: "70", DRMI: "Guásimo", area: "1446,73 ha", ubicacion: "Departamento de Risaralda y Caldas.", autoridad: "Corporación Autónoma Regional de Risaralda (CARDER)", acuerdo: "Acuerdo No 021 del 17 de junio de 2011 \'Por el cual se declara, reserva y alindera el Distrito de Manejo Integrado Guásimo como categoría de área protegida integrante del SINAP\'"},
    {id: "71", DRMI: "Honduras", area: "671,76 ha", ubicacion: "Departamento de Santander", autoridad: "Corporación Autónoma Regional para la Defensa de la Meseta de Bucaramanga (CDMB)", acuerdo: "Resolución 1420 del 17 de diciembre de 2021 Por medio del cual se reserva, delimita, alindera y declara el “DISTRITO REGIONAL DE MANEJO INTEGRADO DRMI “HONDURAS” en jurisdicción de los municipios de Rionegro y Matanza, se adopta el Plan de Manejo y se acuerdan otras disposiciones."},
    {id: "72", DRMI: "Humedales de Gualí Tres Esquinas y Lagunas del Funzhé", area: "1196,39 ha", ubicacion: "Departamento de Cundinamarca", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 001 del 18 de febrero de 2014 \'Por medio del cual se declaran como Distrito Regional de Manejo Integrado (DMI) los terrenos comprendidos por los humedales de Gualí, Tres Esquinas y Lagunas del Funzhé, y su área de influencia directa ubicada en los municipios de Funza, Mosquera y Tenjo, Cundinamarca\'."},
    {id: "73", DRMI: "Isla Ají", area: "\n > 9425,80 ha Terrestre. \n > 15174,20 ha marítimo.", ubicacion: "Departamento del Valle del Cauca.", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Resolución 046 13 de diciembre de 2021 Por el cual se reserva, delimita, alindera y declara el Distrito Regional de Manejo Integrado Isla Ají, localizado en el Distrito Especial, Industrial, Portuario, Biodiverso y Ecoturístico de Buenaventura, se adopta su Plan de Manejo y se dictan otras determinaciones."},
    {id: "74", DRMI: "Juaitoque", area: "400,00 ha", ubicacion: "Departamento de Cundinamarca", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 01 del 21 de enero de 1998 \'Por medio del cual se declara y alinda un Distrito de Manejo Integrado de los Recursos Naturales\' Acuerdo ARTICULO PRIMERO. Declarar como Distrito de Manejo Integrado de los Recursos Naturales los terrenos que conforman las partes altas de las quebradas La Chorrera y Caño Pantanitos, afluentes de la quebrada San Isidro en la jurisdicción del municipio de Cucunubá (Cund.), terrenos que dentro de la presente declaratoria recibirán el nombre de Distrito de Manejo Integrado de los Recursos Naturales de Juaitoque."},
    {id: "75", DRMI: "La Nona", area: "511,85 ha", ubicacion: "Departamento de Risaralda", autoridad: "Corporación Autónoma Regional de Risaralda (CARDER)", acuerdo: "Acuerdo No 019 del 17 de junio de 2011 \'Por el cual se declara, reserva y alindera el Distrito de Manejo Integrado La Nona como categoría de área protegida integrante del SINAP\'"},
    {id: "76", DRMI: "La Selva", area: "64,84 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "Resolución 192 del 21 de junio de 2007 Por la cual se declara como Distrito Regional de MAnejo Integrado de los recursos renaovables DMI el predio donde esta ubicado el centro de investigaciones La Selva, sector Llanogrande del municipio de Rionegro."},
    {id: "77", DRMI: "La Tatacoa", area: "35140,10 ha", ubicacion: "Departamento de Huila y Tolima", autoridad: "Corporación Autónoma Regional del Alto Magdalena (CAM)", acuerdo: "Resolución 017 del 17 de diciembre de 2008 Por el cual se declara la ecorregión de la Tatacoa como PNR y se dictan normas para su administración y manejo sostenible."},
    {id: "78", DRMI: "Lago Azul los Manatìes", area: "30000,00 ha", ubicacion: "Departamento de Chocó y Antioquia", autoridad: "Corporación Autónoma Regional para el Desarrollo Sostenible del Chocó (CODECHOCÓ)", acuerdo: "ACUERDO CONSEJO DIRECTIVO NÚMERO 002 DE MARZO 19 DE 2013. Por medio del cual se declara el Distrito de Manejo Integrado \'Lago Azul - Los Manatíes\' en el municipio de Unguía - Departamento del Chocó y se adopta otras determinaciones."},
    {id: "79", DRMI: "Lago de Sochagota y la cuenca hidrográfica que lo alimenta", area: "8139,11 ha", ubicacion: "Departamento de Boyacá", autoridad: "Corporación Autónoma Regional de Boyacá (CORPOBOYACÁ)", acuerdo: "Resolución 0024 del 31 de julio de 1986 Por el cual se declara Distrito de Manejo Inteqrado y Area de Recreación, el Lago de Sochagota y la cuenca hidrográfica que lo alimenta."},
    {id: "80", DRMI: "Laguna de San Diego", area: "757,28 ha", ubicacion: "Departamento de Caldas", autoridad: "Corporación Autónoma Regional de Caldas (CORPOCALDAS)", acuerdo: "Resolución 19 del 04 de octubre de 2011Por medio del cual se delimita y declara el Distrito Regional de Manejo Integrado de Recursos Naturales Renovables Laguna de San Diego y se dictan normas para su uso y funcionamiento El Consejo Directivo de la Corporación Autónoma Regional de Caldas en uso de sus atribuciones, en especial la que le confiere el literal g) del artículo 27 de la Ley 99 de 1993, en concordancia con el literal p) del artículo 32 de los Estatutos Internos de la Entidad."},
    {id: "81", DRMI: "Laguna de Sonso o del Chircal", area: "2045,00 ha", ubicacion: "Departamento del Valle del Cauca.", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Resolución 17 del 18 de octubre de 1978 Por el cual se declara como zona de Reserva Natural la Laguna de Sonso o del Chircal y zonas aledañas en jurisdicción del municipio de Buga departamento del Valle del Cauca."},
    {id: "82", DRMI: "Laguna la Primavera", area: "17087,20 ha", ubicacion: "Departamento del Vichada", autoridad: "Corporación Autónoma Regional de la Orinoquía (CORPORINOQUIA)", acuerdo: "Resolución 20003 del 30 de octubre de 2020 Por medio del cual se declara como Distrito Regional de Manejo Integrado La Laguna de la Primavera, ubicada en jurisdicción del municipio de la Primavera, Departamento del Vichada."},
    {id: "83", DRMI: "Luriza", area: "837,17 ha", ubicacion: "Departamento del Atlántico.", autoridad: "Corporación Autónoma Regional del Atlántico (CRA)", acuerdo: "Resolución 0003 del 22 de marzo de 2011 Acuerdo mediante el cual se declara el Distrito de Manejo Integrado -DMI Luriza, y se adoptan otras disposiciones. Del Consejo Directivo de la Corporación de fecha 22 de Marzo de 2011."},
    {id: "84", DRMI: "Macizo El Tablazo", area: "16485,77 ha", ubicacion: "Departamento de Cundinamarca.", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 10 del 26 de mayo de 2021 Por medio del cual se declara, delimita y alindera el Distrito Regional de Manejo Integrado Macizo El Tablazo, ubicado en la jurisdicción de la Corporación Autónoma Regional de Cundinamarca - CAR, y se dictan normas para su administración y manejo sostenible."},
    {id: "85", DRMI: "Manglar de la Bahía de Cispatá y Sector Aledaño del Delta Estuarino del Río Sinú", area: "\n > 23125,00 ha terrestres. \n > 4683,00 ha marítima.", ubicacion: "Departamento de Córdoba", autoridad: "Corporación Autónoma Regional de los Valles del Sinú y San Jorge (CVS)", acuerdo: "Resolución 56 del 07 de julio de 2006 Por el cual se reserva, declara, delimita como Distrito de Manejo Integrado el área de Manglar de la Bahía de Cispatá y Sector Aledaño del Delta Estuarino del Río Sinú. El área reservada tendrá una extensión de 27.171 ha y cobija áreas de manglares, humedales, playones y playas."},
    {id: "86", DRMI: "Mata de la Urama", area: "20133,84 ha", ubicacion: "Departamento de Casanare", autoridad: "Corporación Autónoma Regional de la Orinoquía (CORPORINOQUIA)", acuerdo: "Resolución 07008 del 16 de noviembre de 2007 Por medio del cual se declara y se delimita como Distrito de Manejo Integrado de los Recursos Naturales Renovables (D.M.I) el \'Ecosistema Estratégico Mata de la Urama\' y se adoptan otras determinaciones."},
    {id: "87", DRMI: "Mejué", area: "10651,36 ha", ubicacion: "Departamento de Norte de Santander. ", autoridad: "Corporación Autónoma Regional de la Frontera Nororiental (CORPONOR)", acuerdo: "Resolución 026 del 17 de diciembre de 2018 “POR EL CUAL SE DECLARA, RESERVA, DELIMITA Y ALINDERA EL DISTRITO REGIONAL DE MANEJO INTEGRADO (DRMI) MEJUÉ, EN LOS MUNICIPIOS DE CHINÁCOTA, HERRÁN, PAMPLONITA Y TOLEDO, DEPARTAMENTO DE NORTE DE SANTANDER Y SE DICTAN OTRAS DISPOSICIONES"},
    {id: "88", DRMI: "Musichi", area: "1494,40 ha", ubicacion: "Departamento de La Guajira", autoridad: "Corporación Autónoma Regional de la Guajira (CORPOGUAJIRA)", acuerdo: "Resolución 031 del 22 de diciembre de 2011 POR EL CUAL SE DECLARA LA DISTRITO DE MANEJO INTEGRADO MUSICHI UBICADO EN EL MUNICIPIO DE MANAURE, DEPARTAMENTO DE LA GUAJIRA Y SE ADPTAN OTRAS MEDIDAS PARA SU ADMINISTRACIÓN Y MANEJO"},
    {id: "89", DRMI: "Nacimiento de las Quebradas los Tiestos, La Chorrera y Hoya Fría", area: "659,00 ha", ubicacion: "Departamento de Cundinamarca", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 24 del 14 de junio de 2000 \'Por el cual se declara y alindera un Distrito de Manejo Integrado en el Nacimiento de Las Quebradas Los Tiestos, La Chorrera y Hoya Fría, municipio de La Palma, Cundinamarca\'."},
    {id: "90", DRMI: "Nubes Trocha Capota", area: "4184,00 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Acuerdo 352 del 20 de Mayo de 2010, Por el cual se declara, reserva y alindera el Distrito de Manejo Integrado Nubes, Trocha, Capota y se toman otras determinaciones."},
    {id: "91", DRMI: "Palmar del Tití", area: "2622,15 ha", ubicacion: "Departamento de Atlántico", autoridad: "Corporación Autónoma Regional del Atlántico (CRA)", acuerdo: "Resolución 00008 del 30 de julio de 2018 Por el cual se declara el Distrito Regional de Manejo Integrado (DRMI) Palmar del Tití y se adoptan otras disposiciones. El Consejo Directivo de la CORPORACIÓN AUTÓNOMA REGIONAL DEL ATLÁNTICO CRA, en ejercicio de sus facultades legales conferidas por el Decreto 2372 de 2010, por el cual se reglamenta la Ley 99 de 1993, demás normas concordantes"},
    {id: "92", DRMI: "Pance", area: "1405,20 ha", ubicacion: "Departamento del Valle del Cauca.", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Acuerdo No. 105 del 11 de Diciembre de 2017, por medio del cual se declara, reserva, delimita y alindera el Distrito Regional de Manejo Integrado Pance, en el corregimiento de Pance, Municipio de Cali, Valle del Cauca."},
    {id: "93", DRMI: "Páramo Mamapacha y Bijagual", area: "25103,88 ha", ubicacion: "Departamento de Boyacá", autoridad: "Corporación Autónoma Regional de Chivor (CORPOCHIVOR)", acuerdo: "Resolución 8 del 28 de junio de 2017 Por medio del cual se declara, reserva, delimita y alindera el Distrito Regional de Manejo Integrado (DRMI) páramo Mamapacha y Bijagual, en los municipios de Garagoa, Chinavita, Ramiriquí, Tibaná, Ciénega y Viracacha, en jurisdicción de la Corporación Autónoma Regional de Chivor CORPOCHIVOR"},
    {id: "94", DRMI: "Páramo Rabanal", area: "6640,00 ha", ubicacion: "Departamento de Boyacá", autoridad: "Corporación Autónoma Regional de Chivor (CORPOCHIVOR)", acuerdo: "Resolución 04 del 07 de febrero de 2011 Por el cual se declara y alindera el Distrito Regional de Manejo Integrado DRMI Páramo de Rabanal en el Municipio de Ventaquemada en jurisdicción de la Corporación Autónoma Regional de Chivor - CORPOCHIVOR"},
    {id: "95", DRMI: "Páramo de Cristales, Castillejo o Gauchaneque", area: "11574,00 ha", ubicacion: "Departamento de Boyacá y Cundinamarca", autoridad: "Corporación Autónoma Regional de Chivor (CORPOCHIVOR)", acuerdo: "Resolución 029 del 20 de diciembre de 2011 Por el cual se declara, reserva, delimita y alindera el Distrito Regional de Manejo Integrado (DRMI) Páramo de Cristales, Castillejo o Guachaneque, en los municipios de La Capilla, Pachavita, Úmbita y Turmequé en jurisdicción de la Corporación Autónoma Regional de Chivor - CORPOCHIVOR."},
    {id: "96", DRMI: "Páramo de Guargua y Laguna Verde", area: "54690,12 ha", ubicacion: " Departamento de  Cundinamarca y Boyacá", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 22 del 18 de agosto de 2009 “Por el cual se declara como Reserva Forestal Protectora y Distrito de Manejo Integrado (DMI) al Páramo de Guargua y Laguna Verde y se adoptan otras determinaciones"},
    {id: "97", DRMI: "Páramo de Guerrero", area: "3760,00 ha", ubicacion: "Departamento de  Cundinamarca", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 42 del 17 de octubre de 2006 \'Por el cual se declara como Distrito de Manejo Integrado (DMI) a un sector del Páramo de Guerrero y se adoptan otras determinaciones” Acuerda: ARTÍCULO PRIMERO: Declarar como Distrito de Manejo Integrado tres sectores del Páramo de Guerrero, localizados en los municipios de Zipaquirá y Cogua, que corresponden a la zona amortiguación de las zonas de reserva forestales protectoras declaradas mediante el Acuerdo 6 del 26 de mayo de 1992 y el Acuerdo 17 del 20 de noviembre del mismo año, expedidos por la Corporación Autónoma Regional de Cundinamarca - CAR.\'"},
    {id: "98", DRMI: "Páramo de Vida Maitamá - Sonsón", area: "40646,96 ha", ubicacion: "Departamento de  Antioquia y Caldas", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "Resolución 388 del 06 de junio de 2019 Las áreas protegidas son zonas que por su importancia ambiental es regulada y administrada con fines de conservación de los recursos naturales. Las áreas protegidas son declaradas a raíz de iniciativas propias de la comunidad, por sus recursos hídricos, bióticos y biofísicos existentes con el fin de impedir su destrucción y permitir la conservación de especies de plantas, paisajes, ambientes naturales y prácticas culturales, además que la conservación de estos sitios tiene prioridad la protección de la vida y para el consumo humano."},
    {id: "99", DRMI: "Páramos y Bosques Altoandinos de Génova", area: "8367,00 ha", ubicacion: "Departamento del Quindío", autoridad: "Corporación Autónoma Regional del Quindío (CRQ)", acuerdo: "Resolución 008 del 29 de agosto de 2008 Por medio del cual la Corporación Autónoma Regional del Quindío declara el Parque Regional Natural Páramos y Bosques Altoandinos del municipio de Génova."},
    {id: "100", DRMI: "Páramos Las Dominguez, Pan de Azúcar y Valle Bonito", area: "15816,50 ha", ubicacion: "Departamento del Valle del Cauca", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Acuerdo 068 del 27 de Noviembre de 2018 ?por el cual se declara, reserva, delimita y alindera el Distrito Regional de Manejo Integrado Páramos las Domínguez, Pan de azúcar y Valle Bonito; se adopta su plan de manejo y se dictan otras determinaciones."},
    {id: "101", DRMI: "Páramos de Guantiva y la Rusia", area: "125669,69 ha", ubicacion: "Departamento de Santander y Boyacá", autoridad: "Corporación Autónoma Regional de Santander (CAS)", acuerdo: "Resolución 095 del 30 de octubre de 2008 Por el cual se declara y alindera un DMI en el territorio que comprende los páramos de Guantiva y La Rusia, bosques de roble y sus zonas aledañas, localizados en los municipios de Charalá , Coromoro, Encino, Gambita,Mogotes, Onzaga, San Joaquin y Suaita, Departamento de Santander."},
    {id: "102", DRMI: "Pastos Marinos Sawairu", area: "67176,65 ha marítimo", ubicacion: "Departamento de La Guajira", autoridad: "Corporación Autónoma Regional de la Guajira (CORPOGUAJIRA)", acuerdo: "Resolución 019 del 28 de septiembre de 2018 Declarar como Distrito de Manejo Integrado un área de 67.240 ha (calculada con el sistema de proyección Magna Colombia origen Este) de zona marina que incluye principalmente pastos marinos y cuya profundidad se encuentra a una isobata de 20 m con el fin de cubrir áreas asociadas a corales blandos (Octocorales) y así aumentar la protección de otros ecosistemas estratégicos."},
    {id: "103", DRMI: "Planes de San Rafael", area: "510,43 ha", ubicacion: "Departamento de Risaralda", autoridad: "Corporación Autónoma Regional de Risaralda (CARDER)", acuerdo: "Acuerdo No 022 de 17 de junio de 2011 \'Por el cual se declara, reserva y alindera el Distrito de Manejo Integrado Planes de San Rafael como categoría de área protegida integrante del SINAP\'."},
    {id: "104", DRMI: "Quitasol - La Holanda", area: "6887,50 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Resolución 596 del 17 de diciembre de 2020 POR MEDIO DEL CUAL SE DECLARA, RESERVA, DELIMITA Y ALINDERA EL DISTRITO REGIONAL DE MANEJO INTEGRADO QUITASOL LA HOLANDA, El Consejo Directivo de la Corporación Autónoma Regional del Centro de Antioquia."},
    {id: "105", DRMI: "Rio Subachoque y Pantano de Arce", area: "4202,01 ha", ubicacion: "Departamento de Cundinamarca", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 17 del 11 de junio de 1997 \'Por el cual se declara y alinda un Distrito de Manejo Integrado de los Recursos Naturales\' Acuerda ARTÍCULO PRIMERO: Declarar como Distrito de Manejo Integrado de los Recursos Naturales, los terrenos que conforman la cuenca alta de rio Subachoque y la región del Pantano de Arce, ubicados en compresión territorial del municipio de Subachoque Cundinamarca."},
    {id: "106", DRMI: "Rios Barroso y San Juan", area: "3037,00 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Resolución 245 del 20 de diciembre de 2006 Por medio del cual se declara, reserva y delimita como Distrito de Manejo Integrado de los Recursos Naturales los Ríos Barroso y San Juan y se toman otras desiciones."},
    {id: "107", DRMI: "Rut Nativos", area: "10840,00 ha", ubicacion: "Departamento del Valle del Cauca", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Resolución 004 del 19 de marzo de 2015 POR EL CUAL SE DECLARA EL DISTRITO REGIONAL DE MANEJO INTEGRADO RUT-NATIVOS, UBICADO EN LOS MUNICIPIOS DE ROLDANILLO, LA UNIÓN Y TORO, SE ADOPTA SU PLAN DE MANEJO Y SE DICTAN OTRAS DETERMINACIONES."},
    {id: "108", DRMI: "San Miguel", area: "8354, 00 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "ACUERDO Nro. 330 Del 1 de julio de 2015 Por medio del cual se declara el Distrito Regional de Manejo. Integrado San Miguel, sobre áreas identificadas como zonas excluibles de la minería en virtud del Decreto 1374 de 2013 y se dictan otras disposiciones."},
    {id: "109", DRMI: "San Pedro", area: "1184,97 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "Resolución 378 del 04 de octubre de 2018 Por medio del cual se declara el Distrito Regional de Manejo Integrado San Pedro y se dictan otras disposiones. Se declaró como Distrito Regional de Manejo Integrado San Pedro el área de 1184,97 hectáreas, ubicada en el municipio de Concepción, en las veredas: Santa Ana, Santa Gertrudis, Las Frías, San Pedro Peñol Parte Alta y San Pedro Peñol Parte Baja."},
    {id: "110", DRMI: "Sector Salto del Tequendama y Cerro Manjuí", area: "10422,00 ha", ubicacion: "Departamento de Cundinamarca", autoridad: "Corporación Autónoma Regional de Cundinamarca (CAR)", acuerdo: "Resolución 43 del 03 de diciembre de 1999 \'Por el cual se declara y alindera un Distrito de Manejo Integrado de los Recursos Naturales Renovables del Sector Salto del Tequendama – Cerro Manjuí\'."},
    {id: "111", DRMI: "Serranía de Abibe", area: "41594,00 ha", ubicacion: "Departamento de Antioquia y Córdoba", autoridad: "Corporación para el Desarrollo Sostenible de Urabá (CORPOURABÁ)", acuerdo: "Resolución 0019 del 18 de diciembre de 2019 \'Por medio del cual se Declara, Reserva, Delimita y Alindera el Distrito Regional de Manejo Integrado Serranía de Abibe, ubicado en los municipios de Apartadó, Carepa, Chigorodó y Turbo (Departamento de Antioquia) y se toman otras disposiciones\'."},
    {id: "112", DRMI: "Serranía de Los Paraguas", area: "39792,00 ha", ubicacion: "Departamento del Valle del Cauca y Chocó", autoridad: "Corporación Autónoma Regional del Valle del Cauca (CVC)", acuerdo: "Resolución 59 del 26 de diciembre de 2019 Por el cual se reserva, delimita, alindera y declara el distrito regional de manejo integrado serranía de los paraguas - municipios de el Cairo, el Dovio y Versalles, departamento del Valle del Cauca."},
    {id: "113", DRMI: "Serranía de Minas", area: "24449,00 ha", ubicacion: " Departamento del Huila", autoridad: "Corporación Autónoma Regional del Alto Magdalena (CAM)", acuerdo: "Resolución 023 del 15 de diciembre de 2006 POR EL CUAL SE DECLARA EL ECOSISTEMA SERRANIA DE MINAS COMO PARQUE NATURAL REGIONAL Y SE DICTAN NORMAS PARA SU ADMINISTRACION Y MANEJO SOSTENIBLE, EN EL DEPARTAMENTO DEL HUILA."},
    {id: "114", DRMI: "Serranía de Peñas Blancas", area: "32793,00 ha", ubicacion: "Departamento del Huila", autoridad: "Corporación Autónoma Regional del Alto Magdalena (CAM)", acuerdo: "Resolución 003 del 22 de marzo de 2018 Por el cual se declara, reserva, delimita, alindera el Distrito Regional de Manejo Integrado (DRMI) Serranía de Peñas Blancas, ubicado en los municipios de Palestina, Acevedo, Pitalito, Timaná y Suaza en el departamento del Huila."},
    {id: "115", DRMI: "Serranía de Perijá", area: "42158,80 ha", ubicacion: "Departamento de La Guajira", autoridad: "Corporación Autónoma Regional de la Guajira (CORPOGUAJIRA)", acuerdo: "Resolución 030 del 22 de diciembre de 2011 Por el cual se declara el Distrito de Manejo Integrado Serranía de Perijá, ubicado en jurisdicción de los municipios de Barrancas, Fonseca y San Juan del Cesar, departamento de La Guajira y se adoptan otras medidas para su administración y manejo."},
    {id: "116", DRMI: "Serranía de los Yariguíes", area: "419225,00 ha", ubicacion: "Departamento de Santander", autoridad: "Corporación Autónoma Regional de Santander (CAS)", acuerdo: "Acuerdo 00007 del 16 de mayo de 2005, por medio del cual se declara y alindera el Distrito de Manejo Integrado de los recursos naturales renovables (DMI) Serranía de los Yariguies."},
    {id: "117", DRMI: "Sistema Viaho Guayabal", area: "5319,89 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional de las cuencas de los ríos Rionegro y Nare (CORNARE)", acuerdo: "ACUERDO Nro. 331 Del 1 de julio de 2015 Por medio del cual se declara.el Distrito'Regional de Manejo Integrado Sistema Viaho - Guayabal, sobre áreas identificadas como zonas excluibles de la minería en virtud del Decreto 1374 de 2013 y se dictan otras disposiciones."},
    {id: "118", DRMI: "Sistema de Paramos y Bosques Altoandinos del Noroccidente Medio Antioqueño", area: "42587,00 ha", ubicacion: "Departamento de Antioquia", autoridad: "Corporación Autónoma Regional del Centro de Antionquia (CORANTIOQUIA)", acuerdo: "Resolución 282 del 14 de diciembre de 2007 Por medio del cual se declara y se alindera como Distrito de Manejo Integrado de los Recursos Naturales el Sistema de Páramos y Bosques Altoandinos del Noroccidente Medio Antioqueño."},
    {id: "119", DRMI: "De la Playona y la Loma de Caleta", area: "8730,28 ha", ubicacion: "Departamento del Chocó", autoridad: "Corporación Autónoma Regional para el Desarrollo Sostenible del Chocó (CODECHOCÓ)", acuerdo: "CORPORACIÓN AUTÓNOMA REGIONAL PARA EL DESARROLLO SOSTENIBLE DEL CHOCÓ \'CODECHOCO\' ACUERDO C.D. NÚMERO 0002 DE 22 FEB 2012. Por medio del cual se declara el Distrito Regional de Manejo Integrado de la Playona y la Lamoa de Caleta en el mnicipio de Acandí, y se adoptan otras determinaciones."},
]


var drmi = document.querySelectorAll(".group-drmi"); 
var div = document.createElement("DIV")

function showInfo(data) {
    div.innerHTML = `
        <b> DRMI: </b> ${data.DRMI} <br>
        <b> Área Protegida: </b> ${data.area.replace(/\n/g, "<br />")} <br>
        <b> Ubicación: </b> ${data.ubicacion} <br>
        <b> Autoridad Ambiental: </b> ${data.autoridad.replace(/\n/g, "<br />")} <br>
        <b> Acuerdo: </b> ${data.acuerdo}
    `
}

drmi.forEach(el => {
    el.addEventListener("mouseover", (event) => {
        console.log(event)
        for (var i=0; i<data.length; i++) {
            if (data[i].id === event.target.id) {
                showInfo(data[i])
            }   
                           
        }   
    })
})

$(function () {
    $('[data-toggle="tooltip"]').tooltip({
        boundary: "viewport",
        template: `
            <div class="tooltip" role="tooltip" style="width: 28%">
                <div class="arrow"></div>
                <div class="tooltip-inner" 
                    style="
                        max-width: none;
                        background:rgb(235, 235, 235); 
                        color:black; 
                        box-shadow: rgb(207, 207, 207) .5px .5px 4px;
                        text-align: left;
                        font-family: verdana;
                        font-size: 12px;                         
                    ">
                </div>
            </div>`,
        title: div,
    })
})